import{readFileSync}from"node:fs";import{join}from"node:path";import{describe,expect,it}from"vitest";
import{validateCommunicationComponent004E}from"./communication-component-validator";import{validateCommunicationLink004E}from"./communication-link-validator";import{validateInterference004E}from"./interference-validator";import{validateCommunicationFailure004E}from"./communication-failure-validator";
const load=<T>(p:string)=>JSON.parse(readFileSync(join(process.cwd(),p),"utf8"))as T;const ref=[{sourceId:"official",page:1,section:"s"}];
type Summary={inputDrift:boolean;primaryKnowledgeCount:number;visualCount:number;tableCount:number;statusCounts:Record<string,number>;uasSpecificCount:number;gapCount:number;unsupportedInferenceCount:number;canonicalCandidateCount:number;canonicalIdIssued:number;canonicalBaseline:number;runtimeReadiness:string;mutations:Record<string,number>};
describe("FLIGHT-THEORY-004E validation",()=>{
 it("validates the frozen 16/1/1 input split",()=>{const s=load<Summary>("work/flight-theory-validation/004e/results/validation-summary.json");expect(s.inputDrift).toBe(false);expect([s.primaryKnowledgeCount,s.visualCount,s.tableCount]).toEqual([16,1,1]);expect(s.statusCounts).toEqual({VALIDATED_WITH_WARNING:6,VALIDATED:10});});
 it("does not turn a transmitter into a drone controller",()=>{const r=validateCommunicationComponent004E({componentId:"x",componentType:"TRANSMITTER",function:"drone controller sends commands",sourceReferences:ref,rawEvidence:"e",technicalContext:"AVIATION_COMMUNICATION"});expect(r.validationStatus).toBe("BLOCKED");});
 it.each(["drone command/control link","telemetry data link","FPV video link"])("blocks UAS link synthesis: %s",definition=>{expect(validateCommunicationLink004E({linkId:"x",definition,sourceReferences:ref,rawEvidence:"e",technicalContext:"AVIATION_COMMUNICATION"}).validationStatus).toBe("BLOCKED");});
 it("does not infer lost-link from interference",()=>{expect(validateInterference004E({knowledgeId:"x",phenomenon:"RF",effect:"causes lost-link",sourceReferences:ref,rawEvidence:"e",technicalContext:"RF_GENERAL"}).validationStatus).toBe("BLOCKED");});
 it.each(["lost-link triggers failsafe","failsafe triggers RTH","signal loss requires emergency procedure"])("blocks failure response inference: %s",statement=>{expect(validateCommunicationFailure004E({failureId:"x",statement}).validationStatus).toBe("BLOCKED");});
 it("separates the regulatory table and leaves Canonical IDs null",()=>{const t=load<Array<{status:string;canonicalEvidence:boolean}>>("work/flight-theory-validation/004e/results/table-validation.json")[0];const i=load<Array<{canonicalId:null}>>("work/flight-theory-validation/004e/results/canonical-candidate-inventory.json");expect(t).toMatchObject({status:"REGULATORY_ONLY",canonicalEvidence:false});expect(i).toHaveLength(16);expect(i.every(x=>x.canonicalId===null)).toBe(true);});
 it("protects nine gaps without mutation",()=>{const s=load<Summary>("work/flight-theory-validation/004e/results/validation-summary.json");expect(s.gapCount).toBe(9);expect(s.uasSpecificCount).toBe(0);expect(s.unsupportedInferenceCount).toBe(0);expect(s.canonicalCandidateCount).toBe(16);expect(s.canonicalIdIssued).toBe(0);expect(s.canonicalBaseline).toBe(200);expect(s.runtimeReadiness).toBe("READY_FOR_CANONICAL_BUILD_WITH_GAPS");expect(Object.values(s.mutations).every(v=>v===0)).toBe(true);});
});
