import {describe,expect,it} from "vitest";import {buildLegalSourceProvenance,clusterLegalRules,consolidateLegalCluster,createLegalRuleSignature,detectUnsafeOverlap,mergeLegalConditions,mergeLegalExceptions} from ".";import type {LegalCandidateInput} from ".";
const base:LegalCandidateInput={candidateId:"C1",sourceId:"official-law",sourceVersionId:"v1",sourceLocator:"제1조제1항",subject:"조종자",predicate:"준수",object:"기준",normalizedStatement:"조종자는 25kg 초과 장치를 신고해야 한다",factType:"NUMERIC_THRESHOLD",value:25,unit:"kg",operator:"GT",conditions:["사업용"],exceptions:[],applicability:["조종자"],currentnessStatus:"CURRENT_EFFECTIVE",examRelevance:"HIGH",validationStatus:"VALIDATED",conflictStatus:"NO_CONFLICT"};
describe("legal knowledge consolidation",()=>{
 it("creates deterministic signatures and keeps GT distinct from GTE",()=>{expect(createLegalRuleSignature(base)).toEqual(createLegalRuleSignature({...base}));expect(createLegalRuleSignature(base).signature).not.toBe(createLegalRuleSignature({...base,operator:"GTE"}).signature)});
 it("does not merge the same number under different conditions",()=>expect(detectUnsafeOverlap(base,{...base,candidateId:"C2",conditions:["비사업용"]})).toBe(true));
 it("clusters only identical legal meaning",()=>{const clusters=clusterLegalRules([base,{...base,candidateId:"C2",sourceId:"official-decree"},{...base,candidateId:"C3",operator:"GTE"}]);expect(clusters).toHaveLength(2);expect(clusters.find(x=>x.candidateIds.length===2)?.clusterType).toBe("SAME_RULE_DIFFERENT_SOURCE")});
 it("preserves condition, exception and provenance lineage",()=>{const second={...base,candidateId:"C2",sourceId:"official-decree",sourceLocator:"별표 1",exceptions:["군용은 제외"]};const cluster=clusterLegalRules([base])[0];const unit=consolidateLegalCluster(cluster,new Map([[base.candidateId,base]]));expect(unit.primarySourceLocator).toBe("제1조제1항");expect(mergeLegalConditions([base]).conditions[0].sourceCandidateId).toBe("C1");expect(mergeLegalExceptions([second])[0].sourceLocator).toBe("별표 1");expect(buildLegalSourceProvenance([base,second]).sourceCandidateIds).toHaveLength(2)});
 it("blocks unresolved conflicts",()=>{const conflicted={...base,conflictStatus:"UNRESOLVED_CONFLICT"};const cluster=clusterLegalRules([conflicted])[0];expect(consolidateLegalCluster(cluster,new Map([["C1",conflicted]])).status).toBe("BLOCKED_CONFLICT")});
});
