"use client";

import { useEffect, useRef, useState } from "react";
import { createCanarySnapshot, executeCanaryApply, isCanaryTokenMatch, runCanaryPreflight, selectCanaryCandidate, validateCanaryRuntime, type CanaryCandidateInput, type CanaryPromotionPlan } from "@/domain/exam-engine/coverage/autonomous-promotion/canary";
import { DEFAULT_AUTONOMOUS_PROMOTION_POLICY } from "@/domain/exam-engine/coverage/autonomous-promotion/autonomous-promotion-policy";
import type { PromotionGateResult } from "@/domain/exam-engine/coverage/autonomous-promotion/promotion-gate-result";
import { ACTIVE_PACK_CACHE_KEY, KNOWLEDGE_PACK_CACHE_KEY, cacheKnowledgePack, createLocalKnowledgePackRepository } from "@/domain/exam-engine/import/local-knowledge-pack-repository";
import { KNOWLEDGE_GRAPH_APPROVALS_KEY, KNOWLEDGE_GRAPH_RELATIONS_KEY, KNOWLEDGE_GRAPH_REVIEW_AUDIT_KEY, KNOWLEDGE_GRAPH_VERSION_AUDIT_KEY, KNOWLEDGE_GRAPH_VERSIONS_KEY, createLocalKnowledgeGraphPersistenceRepository } from "@/domain/exam-engine/knowledge-graph/local-knowledge-graph-repository";

const PACK_ID = "kr-drone-license:mrm0omvd";
const GRAPH_VERSION_ID = "kg-candidate-kr-drone-license:mrm0omvd-20260730000000000";
const SELECTED_IDS = ["AF-065", "AF-066"];
const BATCH_IDS = ["AF-061", "AF-063", "AF-064", "AF-065", "AF-066", "AF-069", "AF-070", "AF-071", "AF-072", "AF-073", "AF-074", "AF-075", "AF-076", "AF-077"];
const CONFIRMATION_PHRASE = "APPLY AF-065 AF-066";
const APPROVED_BEFORE = 28;
const APPROVED_AFTER = 30;
const CANARY_AUDIT_KEY = "dronepass.canaryPromotionAudit";
const GRAPH_KEYS = [KNOWLEDGE_GRAPH_RELATIONS_KEY, KNOWLEDGE_GRAPH_VERSIONS_KEY, KNOWLEDGE_GRAPH_APPROVALS_KEY, KNOWLEDGE_GRAPH_REVIEW_AUDIT_KEY, KNOWLEDGE_GRAPH_VERSION_AUDIT_KEY];
type Step = "IDLE" | "PREFLIGHT" | "SNAPSHOT" | "APPLYING" | "VALIDATING" | "PASSED" | "ROLLED_BACK" | "FAILED";
type Diagnostics = { origin: string; found: boolean; factCount: number; approved: number; graphVersion: string | null; relations: number; selected: string[] };

export default function AutonomousPromotionCanaryClient() {
  const [diagnostics, setDiagnostics] = useState<Diagnostics | null>(null); const [step, setStep] = useState<Step>("IDLE"); const [running, setRunning] = useState(false); const [dryPassed, setDryPassed] = useState(false); const [token, setToken] = useState(""); const [phrase, setPhrase] = useState(""); const [tokenUsed, setTokenUsed] = useState(false); const [message, setMessage] = useState(""); const [result, setResult] = useState<Record<string, unknown> | null>(null); const sessionToken = useRef("");
  useEffect(() => { sessionToken.current = globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; void inspect(); }, []);

  async function inspect() {
    try { const repository = createLocalKnowledgePackRepository(); const stored = await repository.getActive(); const graph = stored ? await createLocalKnowledgeGraphPersistenceRepository().getActiveGraph(stored.id) : null; const draftFacts = stored?.pack.atomicFacts.filter((fact) => fact.status === "draft") ?? []; const selection = stored ? selectCanaryCandidate(buildCandidates(draftFacts.filter((fact) => BATCH_IDS.includes(fact.id))), stored.pack.atomicFacts) : null; const next = { origin: location.origin, found: stored?.id === PACK_ID, factCount: stored?.pack.atomicFacts.length ?? 0, approved: stored?.pack.atomicFacts.filter((fact) => fact.status === "approved").length ?? 0, graphVersion: graph?.versionId ?? null, relations: graph?.relations.length ?? 0, selected: selection?.selectedFactIds ?? [] }; setDiagnostics(next); return next; }
    catch (error) { setStep("FAILED"); setMessage(normalizeError(error)); return null; }
  }

  async function runDryRun() {
    if (running) return; setRunning(true); setStep("PREFLIGHT"); setMessage(""); setDryPassed(false);
    try { const current = await inspect(); const errors = preconditionErrors(current, false); if (errors.length) throw new Error(errors.join(", ")); setDryPassed(true); setStep("PASSED"); }
    catch (error) { setStep("FAILED"); setMessage(normalizeError(error)); } finally { setRunning(false); }
  }

  async function apply() {
    if (running || tokenUsed) return; setRunning(true); setStep("PREFLIGHT"); setMessage("");
    const keys = [KNOWLEDGE_PACK_CACHE_KEY, ACTIVE_PACK_CACHE_KEY, CANARY_AUDIT_KEY, ...GRAPH_KEYS]; const rawBefore = Object.fromEntries(keys.map((key) => [key, localStorage.getItem(key)])); let snapshotPath = ""; let snapshotId = "";
    try {
      const current = await inspect(); const errors = preconditionErrors(current, true); if (!isCanaryTokenMatch(token, sessionToken.current, dryPassed)) errors.push("CANARY_APPROVAL_TOKEN_REQUIRED"); if (phrase !== CONFIRMATION_PHRASE) errors.push("CANARY_CONFIRMATION_PHRASE_REQUIRED"); if (errors.length) throw new Error(errors.join(", "));
      const packRepository = createLocalKnowledgePackRepository(); const stored = await packRepository.getActive(); const graphRepository = createLocalKnowledgeGraphPersistenceRepository(); if (!stored) throw new Error("PACK_MISSING"); const graph = await graphRepository.getActiveGraph(PACK_ID); if (!graph) throw new Error("ACTIVE_GRAPH_MISSING");
      const facts = stored.pack.atomicFacts; const candidates = buildCandidates(facts.filter((fact) => fact.status === "draft" && BATCH_IDS.includes(fact.id))); const selectedFacts = SELECTED_IDS.map((id) => facts.find((fact) => fact.id === id)); if (selectedFacts.some((fact) => !fact || fact.status !== "draft")) throw new Error("SELECTED_FACT_NOT_DRAFT"); if (selectedFacts[0]?.groupId !== selectedFacts[1]?.groupId || selectedFacts.some((fact) => fact?.groupOperator !== "AND")) throw new Error("ATOMIC_GROUP_MISMATCH");
      const plan: CanaryPromotionPlan = { canaryId: `canary:${PACK_ID}:AF-065+AF-066`, packId: PACK_ID, batchId: "batch-1-question_count", selectedFactIds: SELECTED_IDS, selectionReason: ["next minimal atomic AND group"], policyId: DEFAULT_AUTONOMOUS_PROMOTION_POLICY.policyId, policyVersion: DEFAULT_AUTONOMOUS_PROMOTION_POLICY.version, executionMode: "CANARY", expectedImpact: { approvedIncrease: 2, questionIncrease: 1 }, rollbackConditions: ["ANY_VALIDATION_FAILURE"], status: "PLANNED" };
      const preflight = runCanaryPreflight({ origin: location.origin, expectedPackId: PACK_ID, actualPackId: stored.id, facts, expectedFactCount: 433, expectedApprovedCount: APPROVED_BEFORE, selectedFactIds: SELECTED_IDS, gates: candidates.filter((candidate) => SELECTED_IDS.includes(candidate.fact.id)).map((candidate) => candidate.gate), activeGraphVersionId: graph.versionId, expectedActiveGraphVersionId: GRAPH_VERSION_ID, activeOperation: false, rollbackAvailable: true }); if (!preflight.passed) throw new Error(preflight.failures.join(", "));
      setStep("SNAPSHOT"); const createdAt = new Date().toISOString(); const snapshot = createCanarySnapshot({ origin: location.origin, packId: PACK_ID, selectedFactIds: SELECTED_IDS, activeGraphVersionId: graph.versionId, activeRelationIds: graph.relations.map((relation) => relation.id), auditCountBefore: readArray(CANARY_AUDIT_KEY).length, createdAt, facts }); snapshotId = snapshot.snapshotId;
      const fileName = `canary-before-${createdAt.replace(/[:.]/gu, "-")}.json`; const response = await fetch("/api/admin/local-recovery-artifact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ fileName, payload: { ...snapshot, sourceOrigin: location.origin, fullPackPayload: stored, fullGraphPayload: graph, graphStorage: Object.fromEntries(GRAPH_KEYS.map((key) => [key, localStorage.getItem(key)])), policy: { id: plan.policyId, version: plan.policyVersion } } }) }); if (!response.ok) throw new Error("SNAPSHOT_ARTIFACT_SAVE_FAILED"); const saved = await response.json() as { path?: string }; if (!saved.path) throw new Error("SNAPSHOT_ARTIFACT_PATH_MISSING"); snapshotPath = saved.path;
      setStep("APPLYING"); const execution = executeCanaryApply({ plan, facts, preflight, snapshot, approvalToken: token.trim(), expectedApprovalToken: sessionToken.current, confirmationPhrase: phrase, expectedConfirmationPhrase: CONFIRMATION_PHRASE, origin: location.origin, executedBy: "local-admin", evidenceIds: SELECTED_IDS.map((id) => `batch1:${id}:p22`), validate: (next) => next.length === 433 && next.filter((fact) => fact.status === "approved").length === APPROVED_AFTER ? [] : ["PACK_COUNT_VALIDATION_FAILED"] }); if (execution.status !== "PASSED") throw new Error(execution.errors.join(",") || execution.status);
      cacheKnowledgePack({ ...stored, pack: { ...stored.pack, atomicFacts: execution.facts } }, true); localStorage.setItem(CANARY_AUDIT_KEY, JSON.stringify([...readArray(CANARY_AUDIT_KEY), ...execution.audits]));
      setStep("VALIDATING"); const reread = await packRepository.getActive(); const graphAfter = await graphRepository.getActiveGraph(PACK_ID); if (!reread || !graphAfter) throw new Error("REPOSITORY_RELOAD_FAILED"); const runtime = validateCanaryRuntime(reread.pack, graphAfter.relations, SELECTED_IDS, APPROVED_BEFORE); const graphUnchanged = graphAfter.versionId === graph.versionId && JSON.stringify(graphAfter.relations) === JSON.stringify(graph.relations); if (!runtime.passed || !graphUnchanged || reread.pack.atomicFacts.filter((fact) => fact.status === "approved").length !== APPROVED_AFTER || !SELECTED_IDS.every((id) => reread.pack.atomicFacts.find((fact) => fact.id === id)?.status === "approved")) throw new Error([...runtime.errors, !graphUnchanged ? "GRAPH_CHANGED" : ""].filter(Boolean).join(",") || "POST_APPLY_VALIDATION_FAILED");
      setResult({ finalDecision: "CANARY_PASSED", origin: location.origin, canaryId: plan.canaryId, snapshotId, snapshotPath, selectedFacts: SELECTED_IDS, approvedBefore: APPROVED_BEFORE, approvedAfter: APPROVED_AFTER, auditIds: execution.audits.map((audit) => audit.auditId), compiler: runtime, graph: { unchanged: graphUnchanged, versionId: graphAfter.versionId, relations: graphAfter.relations.length }, refreshPersistence: "PENDING_USER_RELOAD", restartPersistence: "NOT_VERIFIED", rollback: false }); setStep("PASSED"); consumeToken(); await inspect();
    } catch (error) { for (const [key, value] of Object.entries(rawBefore)) { if (value === null) localStorage.removeItem(key); else localStorage.setItem(key, value); } setStep("ROLLED_BACK"); setMessage(`CANARY_ROLLED_BACK: ${normalizeError(error)}${snapshotPath ? `\nRecovery artifact: ${snapshotPath}` : ""}`); setResult({ finalDecision: "CANARY_ROLLED_BACK", snapshotId, snapshotPath, approvedAfter: APPROVED_BEFORE, rollback: true }); consumeToken(); await inspect(); }
    finally { setRunning(false); }
  }

  function consumeToken() { setTokenUsed(true); sessionToken.current = ""; setToken(""); setPhrase(""); setDryPassed(false); }
  const blockers = preconditionErrors(diagnostics, true); if (!dryPassed) blockers.push("Dry-run PASS required"); if (phrase !== CONFIRMATION_PHRASE) blockers.push("Confirmation phrase mismatch"); if (!isCanaryTokenMatch(token, sessionToken.current, dryPassed)) blockers.push("One-time token mismatch"); if (tokenUsed) blockers.push("Session token consumed"); const canApply = !running && blockers.length === 0;
  return <main style={{ maxWidth: 960, margin: "40px auto", padding: 24, fontFamily: "sans-serif" }}><h1>Autonomous Promotion Canary</h1><p><strong>Step:</strong> {step}</p><dl><dt>Origin</dt><dd>{diagnostics?.origin ?? "loading"}</dd><dt>Pack</dt><dd>{diagnostics?.found ? PACK_ID : "MISSING"}</dd><dt>AtomicFact / Approved</dt><dd>{diagnostics?.factCount ?? 0} / {diagnostics?.approved ?? 0}</dd><dt>Canary Unit</dt><dd>{diagnostics?.selected.join(", ") || "none"}</dd><dt>Active Graph</dt><dd>{diagnostics?.graphVersion ?? "none"} / {diagnostics?.relations ?? 0}</dd></dl><button type="button" disabled={running} onClick={() => void runDryRun()}>{running ? `Running: ${step}` : "Run Dry-Run"}</button><h2>Human confirmation</h2><p>Phrase: <code>{CONFIRMATION_PHRASE}</code></p><input aria-label="confirmation phrase" value={phrase} disabled={!dryPassed || tokenUsed} onChange={(event) => setPhrase(event.target.value)} placeholder={CONFIRMATION_PHRASE}/><p>One-time token: <code>{dryPassed && !tokenUsed ? sessionToken.current : "Dry-run PASS 후 표시"}</code></p><input aria-label="one-time token" value={token} disabled={!dryPassed || tokenUsed} onChange={(event) => setToken(event.target.value)} placeholder="paste complete token"/><button type="button" disabled={!canApply} title={blockers.join("; ")} onClick={() => void apply()}>{running ? `Running: ${step}` : "Apply Canary"}</button>{blockers.length > 0 && <ul>{blockers.map((item) => <li key={item}>{item}</li>)}</ul>}{message && <pre>{message}</pre>}{result && <section><h2>Result</h2><pre>{JSON.stringify(result, null, 2)}</pre></section>}<p>토큰은 저장하지 않으며 성공·실패 후 폐기됩니다. 다른 origin의 localStorage는 공유되지 않습니다.</p></main>;
}

function preconditionErrors(value: Diagnostics | null, requireDraftSelection: boolean) { const errors: string[] = []; if (!value) return ["DIAGNOSTICS_MISSING"]; if (value.origin !== "http://localhost:4450") errors.push("ORIGIN_MISMATCH"); if (!value.found) errors.push("PACK_MISSING"); if (value.factCount !== 433) errors.push("FACT_COUNT_MISMATCH"); if (value.approved !== APPROVED_BEFORE) errors.push("APPROVED_COUNT_MISMATCH"); if (value.graphVersion !== GRAPH_VERSION_ID) errors.push("ACTIVE_GRAPH_VERSION_MISMATCH"); if (value.relations !== 11) errors.push("ACTIVE_RELATION_COUNT_MISMATCH"); if (requireDraftSelection && value.selected.join(",") !== SELECTED_IDS.join(",")) errors.push("CANARY_SELECTION_MISMATCH"); return errors; }
function gate(id: string): PromotionGateResult { return { candidateFactId: id, result: "SAFE_TO_PROMOTE", policyVersion: DEFAULT_AUTONOMOUS_PROMOTION_POLICY.version, promotionScore: id === "AF-076" ? 0.98 : 0.95, evidenceScore: id === "AF-076" ? 0.99 : 0.95, passedRules: [], failedRules: [], blockers: [], warnings: [], recommendedAction: "PROMOTE" }; }
function buildCandidates(facts: Parameters<typeof selectCanaryCandidate>[1]): CanaryCandidateInput[] { return facts.map((fact) => ({ fact, gate: gate(fact.id), evidence: [{ evidenceId: `batch1:${fact.id}:p22`, sourceId: "ts-drone-aviation-safety-2021", sourceType: "OFFICIAL_DOCUMENT", sourceLocator: `${fact.sourceReferences[0]?.locator} ${fact.sourceReferences[0]?.note ?? ""}`, sourceVersion: fact.sourceReferences[0]?.revisionId, confidence: fact.id === "AF-076" ? 0.99 : 0.95, official: true }], compilerReady: true })); }
function readArray(key: string): unknown[] { try { const parsed = JSON.parse(localStorage.getItem(key) ?? "[]"); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function normalizeError(error: unknown) { return error instanceof Error ? error.message : String(error); }
