export type IngestionStatus = "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "PARTIAL" | "FAILED" | "BLOCKED";
export type LegalNodeType = "PART" | "CHAPTER" | "SECTION" | "SUBSECTION" | "ARTICLE" | "PARAGRAPH" | "ITEM" | "SUBITEM" | "APPENDIX" | "FORM" | "ADDENDUM" | "AMENDMENT" | "AMENDMENT_REASON";
export type RepresentationComparison = "MATCH" | "MINOR_FORMAT_DIFFERENCE" | "SUBSTANTIVE_DIFFERENCE" | "MISSING_IN_HTML" | "MISSING_IN_PDF";
export type LegalFactType = "DEFINITION" | "REQUIREMENT" | "PROHIBITION" | "PERMISSION" | "OBLIGATION" | "NUMERIC_THRESHOLD" | "DEADLINE" | "PENALTY" | "ADMINISTRATIVE_SANCTION" | "EXCEPTION" | "COMPOSITE_FACT" | "CROSS_REFERENCE";
export type LegalOperator = "GTE" | "LTE" | "GT" | "LT" | "WITHIN" | "BEFORE" | "AFTER" | "PER_ITEM" | "AGGREGATE" | "EQ" | "NONE";

export type SourceExtractionPolicy = { htmlPreferred: boolean; pdfStructureVerification: boolean; allowOcrWithoutTextLayer: boolean; minimumQuality: number; resume: boolean };
export type SourceIngestionInput = { job: { jobId: string; sourceId: string; adapter: string; localPath: string | null }; sourceVersionId: string; metadata: { checksum: string; effectiveDate: string; authority: string }; files: { html?: string; pdf?: string }; policy: SourceExtractionPolicy };
export type SourceIngestionResult = { jobId: string; sourceId: string; sourceVersionId: string; inputFiles: string[]; pagesProcessed: number; htmlSectionsProcessed: number; articlesExtracted: number; paragraphsExtracted: number; tablesDetected: number; tablesExtracted: number; attachmentsDetected: number; factCandidatesGenerated: number; relationCandidatesGenerated: number; conflictsDetected: number; warnings: string[]; errors: string[]; extractionQuality: ExtractionQuality; status: IngestionStatus };

export type LegalNode = { nodeId: string; sourceId: string; sourceVersionId: string; nodeType: LegalNodeType; title?: string; articleNumber?: string; paragraphNumber?: string; itemNumber?: string; subItemNumber?: string; rawText: string; normalizedText: string; parentNodeId?: string; childNodeIds: string[]; sourceLocator: string; page?: number; htmlAnchor?: string; order: number };
export type NumericValue = { raw: string; value: number; upperValue?: number; unit: string; operator: LegalOperator };
export type LegalFactCandidate = { candidateId: string; sourceId: string; sourceVersionId: string; sourceAuthority: string; sourceLocator: string; subject: string; predicate: string; object: string; value?: number; unit?: string; operator: LegalOperator; conditions: string[]; exceptions: string[]; applicability: string[]; effectiveDate: string; expirationDate?: string; citedArticles: string[]; factType: LegalFactType; groupId: string; groupOperator: "AND" | "OR" | "XOR" | "SEQUENCE" | "NONE"; standaloneQuestionAllowed: boolean; rawEvidenceText: string; normalizedStatement: string; extractionConfidence: number; legalStructureConfidence: number; tableStructureConfidence: number; currentnessStatus: "CURRENT_EFFECTIVE"; warnings: string[]; blockers: string[] };
export type TableRecord = { tableId: string; sourceId: string; sourceLocator: string; pageRange: number[]; title: string; headers: string[]; rows: string[][]; mergedCells: string[]; footnotes: string[]; rowGroups: string[]; columnGroups: string[]; extractionConfidence: number; visualVerificationRequired: boolean };
export type LegalRelationCandidate = { relationCandidateId: string; sourceNodeId: string; targetSourceNodeId?: string; relationType: "DELEGATES_TO" | "IMPLEMENTED_BY" | "DEFINED_IN" | "REQUIRES_RULE" | "REFERENCES" | "EXCEPTION_DEFINED_IN" | "PENALTY_FOR" | "SANCTION_FOR"; evidenceText: string; sourceLocator: string; confidence: number; status: "CANDIDATE" | "UNRESOLVED_REFERENCE" };
export type LegalConflict = { conflictId: string; candidateId?: string; factId?: string; type: "VALUE_CONFLICT" | "OPERATOR_CONFLICT" | "UNIT_CONFLICT" | "CONDITION_CONFLICT" | "EXCEPTION_CONFLICT" | "SCOPE_CONFLICT" | "EFFECTIVE_DATE_CONFLICT" | "SOURCE_AUTHORITY_CONFLICT" | "DUPLICATE_CANDIDATE" | "CROSS_LAW_CONFLICT"; currentEvidence: string; existingEvidence: string; resolution: "REVIEW_REQUIRED"; preferredAuthority: "CURRENT_OFFICIAL_LAW" };
export type ExtractionQuality = { articleExtractionRate: number; paragraphExtractionRate: number; tableDetectionRate: number; tableExtractionRate: number; locatorCompleteness: number; numericPreservationRate: number; conditionPreservationRate: number; exceptionPreservationRate: number; htmlPdfAgreementRate: number; unresolvedReferenceRate: number; extractionQualityScore: number };
export type HtmlPdfComparison = { sourceId: string; sourceLocator: string; htmlChecksum?: string; pdfChecksum?: string; agreement: number; result: RepresentationComparison; differences: string[] };
