import { extractLegalAttachmentReferences } from "./legal-attachment-extractor";
import { compareLegalRepresentations } from "./legal-document-ingestor";
import { buildLegalFactCandidates } from "./legal-fact-candidate-builder";
import { ingestLegalHtml } from "./legal-html-ingestor";
import { ingestLegalPdf, type PdfPageInput } from "./legal-pdf-ingestor";
import { parseLegalStructure } from "./legal-structure-parser";
import { extractLegalTables } from "./legal-table-extractor";
import type { ExtractionQuality, LegalRelationCandidate, SourceIngestionInput, SourceIngestionResult } from "./ingestion-types";

export type SourceIngestionPayload={result:SourceIngestionResult;nodes:ReturnType<typeof parseLegalStructure>;tables:ReturnType<typeof extractLegalTables>["tables"];factCandidates:ReturnType<typeof buildLegalFactCandidates>;relationCandidates:LegalRelationCandidate[];comparisons:ReturnType<typeof compareLegalRepresentations>;attachmentReferences:ReturnType<typeof extractLegalAttachmentReferences>};

export function runSourceIngestion(input:SourceIngestionInput,representations:{html:string;pdfPages:PdfPageInput[]}):SourceIngestionPayload {
  if(!input.files.pdf||!representations.pdfPages.length) return blocked(input,"PDF_INPUT_MISSING");
  const html=ingestLegalHtml(representations.html);
  const pdf=ingestLegalPdf(representations.pdfPages);
  const nodes=parseLegalStructure({sourceId:input.job.sourceId,sourceVersionId:input.sourceVersionId,pages:pdf.pages});
  const tables=extractLegalTables(input.job.sourceId,pdf.pages);
  const factCandidates=buildLegalFactCandidates(nodes,input.metadata);
  const relationCandidates=buildReferenceRelations(nodes);
  const comparisons=compareLegalRepresentations(input.job.sourceId,html,pdf);
  const attachmentReferences=extractLegalAttachmentReferences(pdf.pages.map((page)=>page.text).join("\n"));
  const quality=scoreQuality(nodes,tables,pdf,comparisons,relationCandidates,factCandidates);
  const warnings=[...tables.warnings,...comparisons.flatMap((comparison)=>comparison.differences)];
  const status=input.job.adapter==="LEGAL_TABLE"&&tables.detected>0&&tables.tables.length===0?"PARTIAL":warnings.length?"COMPLETED_WITH_WARNINGS":"COMPLETED";
  return {result:{jobId:input.job.jobId,sourceId:input.job.sourceId,sourceVersionId:input.sourceVersionId,inputFiles:Object.values(input.files).filter((file):file is string=>Boolean(file)),pagesProcessed:pdf.pages.length,htmlSectionsProcessed:html.sections.length,articlesExtracted:nodes.filter((node)=>node.nodeType==="ARTICLE").length,paragraphsExtracted:nodes.filter((node)=>node.nodeType==="PARAGRAPH").length,tablesDetected:tables.detected,tablesExtracted:tables.tables.length,attachmentsDetected:attachmentReferences.length,factCandidatesGenerated:factCandidates.length,relationCandidatesGenerated:relationCandidates.length,conflictsDetected:0,warnings,errors:[],extractionQuality:quality,status},nodes,tables:tables.tables,factCandidates,relationCandidates,comparisons,attachmentReferences};
}

function buildReferenceRelations(nodes:ReturnType<typeof parseLegalStructure>):LegalRelationCandidate[]{const relations:LegalRelationCandidate[]=[];const targets=new Map(nodes.filter((node)=>node.nodeType==="ARTICLE").map((node)=>[node.sourceLocator,node.nodeId]));for(const node of nodes){for(const match of node.normalizedText.matchAll(/(?:\uBC95|\uC601|\uADDC\uCE59)?\s*\uC81C\d+\uC870(?:\uC758\d+)?(?:\uC81C\d+\uD56D)?/g)){const article=match[0].match(/\uC81C(\d+)\uC870(?:\uC758(\d+))?/);if(!article)continue;const locator=`\uC81C${article[1]}\uC870${article[2]?`\uC758${article[2]}`:""}`;const target=targets.get(locator);if(target===node.nodeId)continue;relations.push({relationCandidateId:`LRC-${node.sourceId}-${relations.length+1}`,sourceNodeId:node.nodeId,targetSourceNodeId:target,relationType:"REFERENCES",evidenceText:match[0],sourceLocator:node.sourceLocator,confidence:target?0.88:0.72,status:target?"CANDIDATE":"UNRESOLVED_REFERENCE"});}}return relations;}
function scoreQuality(nodes:ReturnType<typeof parseLegalStructure>,tables:ReturnType<typeof extractLegalTables>,pdf:ReturnType<typeof ingestLegalPdf>,comparisons:ReturnType<typeof compareLegalRepresentations>,relations:LegalRelationCandidate[],facts:ReturnType<typeof buildLegalFactCandidates>):ExtractionQuality {const articleCount=nodes.filter((node)=>node.nodeType==="ARTICLE").length;const locator=nodes.length?nodes.filter((node)=>node.sourceLocator&&node.page).length/nodes.length:0;const numeric=facts.filter((fact)=>/\d/.test(fact.rawEvidenceText));const conditions=facts.filter((fact)=>/\uACBD\uC6B0|\uB54C\uC5D0|\uB530\uB77C/.test(fact.rawEvidenceText));const exceptions=facts.filter((fact)=>/\uB2E4\uB9CC|\uC81C\uC678/.test(fact.rawEvidenceText));const values={articleExtractionRate:articleCount?1:0,paragraphExtractionRate:articleCount?nodes.filter((node)=>node.nodeType==="PARAGRAPH").length/articleCount:0,tableDetectionRate:tables.detected?1:0,tableExtractionRate:tables.detected?tables.tables.length/tables.detected:1,locatorCompleteness:locator,numericPreservationRate:numeric.length?numeric.filter((fact)=>fact.value!==undefined&&fact.unit).length/numeric.length:1,conditionPreservationRate:conditions.length?conditions.filter((fact)=>fact.conditions.length).length/conditions.length:1,exceptionPreservationRate:exceptions.length?exceptions.filter((fact)=>fact.exceptions.length).length/exceptions.length:1,htmlPdfAgreementRate:comparisons.reduce((sum,item)=>sum+item.agreement,0)/Math.max(comparisons.length,1),unresolvedReferenceRate:relations.length?relations.filter((relation)=>relation.status==="UNRESOLVED_REFERENCE").length/relations.length:0,extractionQualityScore:0};values.extractionQualityScore=round(values.articleExtractionRate*.18+Math.min(values.paragraphExtractionRate,1)*.12+values.tableExtractionRate*.12+values.locatorCompleteness*.15+values.numericPreservationRate*.15+values.conditionPreservationRate*.08+values.exceptionPreservationRate*.08+values.htmlPdfAgreementRate*.07+(1-values.unresolvedReferenceRate)*.05);return values;}
function blocked(input:SourceIngestionInput,error:string):SourceIngestionPayload {const quality={articleExtractionRate:0,paragraphExtractionRate:0,tableDetectionRate:0,tableExtractionRate:0,locatorCompleteness:0,numericPreservationRate:0,conditionPreservationRate:0,exceptionPreservationRate:0,htmlPdfAgreementRate:0,unresolvedReferenceRate:0,extractionQualityScore:0};return{result:{jobId:input.job.jobId,sourceId:input.job.sourceId,sourceVersionId:input.sourceVersionId,inputFiles:[],pagesProcessed:0,htmlSectionsProcessed:0,articlesExtracted:0,paragraphsExtracted:0,tablesDetected:0,tablesExtracted:0,attachmentsDetected:0,factCandidatesGenerated:0,relationCandidatesGenerated:0,conflictsDetected:0,warnings:[],errors:[error],extractionQuality:quality,status:"BLOCKED"},nodes:[],tables:[],factCandidates:[],relationCandidates:[],comparisons:[],attachmentReferences:[]};}
function round(value:number){return Math.round(value*10000)/10000;}
