import { describe,expect,it } from "vitest";
import { compareLegalRevisions } from "./legal-revision-comparator";
import { detectLegalConflicts } from "./legal-conflict-detector";
import { buildLegalFactCandidates,extractNumericValues } from "./legal-fact-candidate-builder";
import { parseLegalStructure } from "./legal-structure-parser";
import { runSourceIngestion } from "./source-ingestion-runner";
import { extractLegalTables } from "./legal-table-extractor";

const text="\uC81C129\uC870(\uC2E0\uACE0) \u2460 \uC0AC\uC5C5\uC790\uB294 \uCD5C\uB300\uC774\uB959\uC911\uB7C9 25kg \uC774\uD558\uC778 \uACBD\uC6B0 \uC2E0\uACE0\uD558\uC5EC\uC57C \uD55C\uB2E4. \uB2E4\uB9CC, \uBCC4\uD45C 6\uC5D0\uC11C \uC815\uD558\uB294 \uACBD\uC6B0\uB294 \uC81C\uC678\uD55C\uB2E4.\n1. \uC2E0\uACE0\uC11C\uB97C \uC81C\uCD9C\uD560 \uAC83";
describe("source ingestion",()=>{
  it("preserves article/paragraph/item hierarchy and locators",()=>{const nodes=parseLegalStructure({sourceId:"law",sourceVersionId:"v1",pages:[{page:7,text}]});expect(nodes.some((node)=>node.nodeType==="ARTICLE"&&node.sourceLocator==="\uC81C129\uC870")).toBe(true);expect(nodes.some((node)=>node.nodeType==="PARAGRAPH"&&node.parentNodeId)).toBe(true);expect(nodes.some((node)=>node.nodeType==="ITEM"&&node.sourceLocator.includes("\uC81C1\uD638"))).toBe(true);});
  it("preserves numeric value, unit, operator, condition and exception",()=>{const nodes=parseLegalStructure({sourceId:"law",sourceVersionId:"v1",pages:[{page:7,text}]});const facts=buildLegalFactCandidates(nodes,{authority:"OFFICIAL_LAW",effectiveDate:"2026-07-01"});expect(extractNumericValues(text)[0]).toMatchObject({value:25,unit:"kg",operator:"LTE"});expect(facts.some((fact)=>fact.conditions.length&&fact.exceptions.length)).toBe(true);});
  it("merges representations and marks missing dynamic HTML",()=>{const payload=runSourceIngestion({job:{jobId:"j",sourceId:"law",adapter:"LEGAL_TEXT",localPath:"law.pdf"},sourceVersionId:"v1",metadata:{checksum:"x",effectiveDate:"2026-07-01",authority:"OFFICIAL_LAW"},files:{html:"<html>shell</html>",pdf:"law.pdf"},policy:{htmlPreferred:true,pdfStructureVerification:true,allowOcrWithoutTextLayer:true,minimumQuality:.7,resume:true}},{html:"<html>shell</html>",pdfPages:[{page:7,text,words:[{text:"25kg",x0:1,x1:2,top:1,bottom:2}],lines:0}]});expect(payload.comparisons[0].result).toBe("MISSING_IN_HTML");expect(payload.result.status).toBe("COMPLETED_WITH_WARNINGS");});
  it("detects revisions and conflicts without mutating facts",()=>{const nodes=parseLegalStructure({sourceId:"law",sourceVersionId:"v1",pages:[{page:7,text}]});const candidates=buildLegalFactCandidates(nodes,{authority:"OFFICIAL_LAW",effectiveDate:"2026-07-01"});const facts=[{id:"AF-X",statement:text.replace("25kg","30kg"),value:30,operator:"lte",sourceDocumentId:"old"}];const before=JSON.stringify(facts);expect(compareLegalRevisions(candidates,facts)[0].status).toBe("UPDATED_VALUE");expect(detectLegalConflicts(candidates,facts).some((item)=>item.type==="VALUE_CONFLICT")).toBe(true);expect(JSON.stringify(facts)).toBe(before);});
  it("keeps table coordinates and merged-cell risk visible",()=>{const result=extractLegalTables("law",[{page:2,text:"\uBCC4\uD45C 1 \uAE30\uC900\uD45C",lines:3,words:[{text:"\uAD6C\uBD84",x0:1,x1:2,top:1,bottom:2},{text:"\uAE30\uC900",x0:20,x1:30,top:1,bottom:2},{text:"A",x0:1,x1:2,top:10,bottom:11},{text:"25kg",x0:20,x1:30,top:10,bottom:11}]}]);expect(result.tables).toHaveLength(1);expect(result.tables[0].visualVerificationRequired).toBe(true);});
  it("deduplicates candidates and blocks unvalidated promotion",()=>{const nodes=parseLegalStructure({sourceId:"law",sourceVersionId:"v1",pages:[{page:7,text},{page:7,text}]});const facts=buildLegalFactCandidates(nodes,{authority:"OFFICIAL_LAW",effectiveDate:"2026-07-01"});expect(new Set(facts.map((fact)=>`${fact.sourceLocator}|${fact.normalizedStatement}`)).size).toBe(facts.length);expect(facts.every((fact)=>fact.blockers.includes("SOURCE_INGESTION_UNVALIDATED"))).toBe(true);});
});
