export type CanonicalQuestionEligibility="STANDALONE"|"RELATIONSHIP_REQUIRED"|"VISUAL_REQUIRED"|"NOT_QUESTION_ELIGIBLE";
export type CanonicalFlightUnit={knowledgeId:string;knowledgeType:string;title:string;definitionOrStatement:string;phase?:string;steps?:string[];ordered?:boolean;checklistItem?:string;monitoredCondition?:string;trigger?:string;decision?:string;safetyAction?:string;structure?:string;components?:string[];relationships?:string[];topic:string;properties:string[];variables:string[];units:string[];inputs:string[];mechanism:string;outputs:string[];conditions:string[];limitations:string[];formula?:string;sourceReferences:unknown[];relationshipIds:string[];visualAssetIds:string[];questionEligibility:CanonicalQuestionEligibility;supportedQuestionTypes:string[];qualityScore:number;warnings:string[]};
export type CanonicalFlightKnowledgeSet={setId:string;version:string;batchId:"004A"|"004B"|"004F"|"004G";sourceSnapshotId:string;conceptIds:string[];principleIds:string[];formulaIds:string[];componentIds?:string[];systemIds?:string[];relationshipIds:string[];blockedIds:string[];warningIds:string[];topicCoverage:unknown[];generatedAt:string;checksum:string;units:CanonicalFlightUnit[]};

export type Canonical004GKnowledgeType="FAILURE_MODE"|"FAILURE_SYMPTOM"|"EMERGENCY_PROCEDURE"|"EMERGENCY_DECISION"|"SAFETY_KNOWLEDGE"|"FLIGHT_CONCEPT"|"RELATIONSHIP";
export type Canonical004GUnit=Record<string,unknown>&{knowledgeId:string;sourceRecordId:string;knowledgeType:Canonical004GKnowledgeType;title:string;sourceReferences:unknown[];relationshipIds:string[];qualityScore:number;validationWarnings:string[];constraints:Record<string,boolean>;supportedQuestionTypes:string[];questionEligibility:"STANDALONE"|"RELATIONSHIP_REQUIRED"};
export type CanonicalFlight004GSet={setId:"canonical-flight-theory:004g:v1";version:"1";batchId:"004G";canonicalUnits:Canonical004GUnit[];relationshipUnits:Canonical004GUnit[];warningIds:string[];excludedIds:string[];topicCoverage:unknown[];runtimeReadiness:unknown;sourceSnapshot:unknown;generatedAt:string;checksum:string};
export type Canonical004HKnowledgeType="HUMAN_FACTOR"|"RISK_MANAGEMENT"|"CREW_COORDINATION"|"MAINTENANCE"|"INSPECTION"|"SAFETY_KNOWLEDGE"|"FLIGHT_CONCEPT"|"RELATIONSHIP";
export type Canonical004HUnit=Record<string,unknown>&{knowledgeId:string;sourceRecordId:string;knowledgeType:Canonical004HKnowledgeType;title:string;sourceReferences:unknown[];relationshipIds:string[];questionEligibility:"STANDALONE"|"RELATIONSHIP_REQUIRED";supportedQuestionTypes:string[];qualityScore:number;warnings:string[]};
export type CanonicalFlight004HSet={setId:"canonical-flight-theory:004h:v1";version:"1";batchId:"004H";canonicalUnits:Canonical004HUnit[];relationshipUnits:Canonical004HUnit[];warningIds:string[];blockedIds:string[];topicCoverage:unknown[];runtimeReadiness:unknown;sourceSnapshot:unknown;generatedAt:string;checksum:string};
