import { readFile } from "node:fs/promises";
import { join } from "node:path";
import DroneSourceCoverageClient from "./source-coverage-client";

export const dynamic = "force-dynamic";

export default async function Page() {
  const ingestionSummary = await loadIngestionSummary();
  const annexSummary = await loadAnnexSummary();
  const attachments = await loadJson<AttachmentRecord[]>("work/source-ingestion/source-batch-002/attachments.json", []);
  const precisionSummary = await loadJson<PrecisionIngestionSummary | null>("work/source-ingestion/source-batch-002a/ingestion-summary.json", null);
  const tableSummary = await loadJson<TableValidationSummary | null>("work/source-ingestion/source-batch-002b/ingestion-summary.json", null);
  const tableMetrics = await loadJson<Record<string, number>>("work/source-ingestion/source-batch-002b/quality-metrics.json", {});
  const tableReviewQueue = await loadJson<TableReviewItem[]>("work/source-ingestion/source-batch-002b/manual-table-review-queue.json", []);
  const validationManifest = await loadJson<LegalValidationManifest | null>("work/legal-validation/validation-input-manifest.json", null);
  const validationBatches = await loadJson<LegalValidationBatch[]>("work/legal-validation/validation-batches.json", []);
  const validationSummary = await loadJson<LegalValidationSummary | null>("work/legal-validation/results/combined/validation-summary.json", null);
  const topicCoverage = await loadJson<LegalTopicCoverage[]>("work/legal-validation/results/combined/topic-coverage.json", []);
  const consolidationSummary = await loadJson<LegalConsolidationSummary | null>("work/legal-knowledge-consolidation/consolidation-summary.json", null);
  const canonicalTopicCoverage = await loadJson<CanonicalTopicCoverage[]>("work/legal-knowledge-consolidation/topic-coverage.json", []);
  const topicGaps = await loadJson<TopicGap[]>("work/legal-knowledge-consolidation/topic-gap-analysis.json", []);
  const shadowSummary = await loadJson<ShadowRuntimeSummary | null>("work/legal-shadow-pack/shadow-runtime-summary.json", null);
  const hardeningSummary = await loadJson<RuntimeHardeningSummary | null>("work/legal-runtime-hardening/runtime-summary.json", null);
  const weatherSummary = await loadJson<WeatherSourceSummary | null>("work/source-ingestion/source-batch-003/summary.json", null);
  const weatherBatches = await loadJson<WeatherBatchSummary[]>("work/source-ingestion/source-batch-003/batch-plan.json", []);
  const weatherIngestion = await loadJson<WeatherIngestionSummary | null>("work/source-ingestion/source-batch-003/ingestion/summary.json", null);
  const weatherIngestionBatches = await loadJson<WeatherIngestionBatch[]>("work/source-ingestion/source-batch-003/ingestion/batch-status.json", []);
  const weatherReconciliation = await loadJson<WeatherReconciliationSummary | null>("work/weather-reconciliation/reconciliation-summary.json", null);
  const weatherRecovery = await loadJson<WeatherRecoverySummary | null>("work/weather-code-recovery/summary.json", null);
  const weatherHazardObservationRecovery = await loadJson<WeatherHazardObservationRecoverySummary | null>("work/weather-hazard-observation-recovery/summary.json", null);
  const weatherRuntime = await loadJson<WeatherShadowRuntimeSummary | null>("work/weather-shadow-runtime/runtime-summary.json", null);
  const flightTheorySource = await loadJson<FlightTheorySourceSummary | null>("work/source-ingestion/source-batch-004/summary.json", null);
  const flightTheoryCde = await loadJson<FlightTheoryCdeSummary | null>("work/source-ingestion/source-batch-004cde/summary.json", null);
  const flight004C = await loadJson<FlightTheory004CSummary | null>("work/source-ingestion/source-batch-004c/ingestion-summary.json", null);
  const flight004CValidation = await loadJson<FlightTheory004CValidationSummary | null>("work/flight-theory-validation/004c/results/validation-summary.json", null);
  const flight004CCanonical = await loadJson<FlightTheory004CCanonicalSummary | null>("work/flight-theory-validation/004c/results/canonical-summary.json", null);
  const flight004D = await loadJson<FlightTheory004DSummary | null>("work/source-ingestion/source-batch-004d/ingestion-summary.json", null);
  const flight004DValidation = await loadJson<FlightTheory004DValidationSummary | null>("work/flight-theory-validation/004d/results/validation-summary.json", null);
  const flight004DCanonical = await loadJson<FlightTheory004DCanonicalSummary | null>("work/flight-theory-validation/004d/results/canonical-summary.json", null);
  const flight004E = await loadJson<FlightTheory004ESummary | null>("work/source-ingestion/source-batch-004e/ingestion-summary.json", null);
  const flight004EValidation = await loadJson<FlightTheory004EValidationSummary | null>("work/flight-theory-validation/004e/results/validation-summary.json", null);
  const flight004A = await loadJson<FlightTheory004ASummary | null>("work/source-ingestion/source-batch-004a/ingestion-summary.json", null);
  const flight004AValidation = await loadJson<FlightTheory004AValidationSummary | null>("work/flight-theory-validation/004a/results/validation-summary.json", null);
  const flight004B = await loadJson<FlightTheory004BSummary | null>("work/source-ingestion/source-batch-004b/ingestion-summary.json", null);
  const flight004BValidation = await loadJson<FlightTheory004BValidationSummary | null>("work/flight-theory-validation/004b/results/summary.json", null);
  const flight004F = await loadJson<FlightTheory004FSummary | null>("work/source-ingestion/source-batch-004f/ingestion-summary.json", null);
  const flight004FValidation = await loadJson<FlightTheory004FValidationSummary | null>("work/flight-theory-validation/004f/results/validation-summary.json", null);
  const flight004G = await loadJson<FlightTheory004GSummary | null>("work/source-ingestion/source-batch-004g/ingestion-summary.json", null);
  const flight004GCanonical = await loadJson<FlightTheory004GCanonicalSummary | null>("work/flight-theory-validation/004g/results/canonical-summary.json", null);
  const flight004H = await loadJson<FlightTheory004HSummary | null>("work/source-ingestion/source-batch-004h/ingestion-summary.json", null);
  const flight004HValidation = await loadJson<FlightTheory004HValidationSummary | null>("work/flight-theory-validation/004h/results/validation-summary.json", null);
  return <><DroneSourceCoverageClient flightTheoryCde={flightTheoryCde} flight004C={flight004C} flight004CValidation={flight004CValidation} flight004CCanonical={flight004CCanonical} flight004D={flight004D} flight004DValidation={flight004DValidation} flight004DCanonical={flight004DCanonical} flight004E={flight004E} ingestionSummary={ingestionSummary} annexSummary={annexSummary} attachments={attachments} precisionSummary={precisionSummary} tableSummary={tableSummary} tableMetrics={tableMetrics} tableReviewQueue={tableReviewQueue} validationManifest={validationManifest} validationBatches={validationBatches} validationSummary={validationSummary} topicCoverage={topicCoverage} consolidationSummary={consolidationSummary} canonicalTopicCoverage={canonicalTopicCoverage} topicGaps={topicGaps} shadowSummary={shadowSummary} hardeningSummary={hardeningSummary} weatherSummary={weatherSummary} weatherBatches={weatherBatches} weatherIngestion={weatherIngestion} weatherIngestionBatches={weatherIngestionBatches} weatherReconciliation={weatherReconciliation} weatherRecovery={weatherRecovery} weatherHazardObservationRecovery={weatherHazardObservationRecovery} weatherRuntime={weatherRuntime} flightTheorySource={flightTheorySource} flight004A={flight004A} flight004AValidation={flight004AValidation} flight004B={flight004B} flight004BValidation={flight004BValidation} flight004F={flight004F} flight004FValidation={flight004FValidation} flight004G={flight004G} flight004GCanonical={flight004GCanonical} flight004H={flight004H} flight004HValidation={flight004HValidation} /><Flight004EValidationPanel summary={flight004EValidation}/></>;
}

function Flight004EValidationPanel({summary}:{summary:FlightTheory004EValidationSummary|null}){if(!summary)return null;return <section style={{margin:"24px auto",maxWidth:1120,padding:20,border:"1px solid #cbd5e1",borderRadius:12}}><h2>FLIGHT-THEORY-004E Validation (read-only)</h2><p><strong>Input:</strong> Knowledge {summary.primaryKnowledgeCount} / Visual {summary.visualCount} / Table {summary.tableCount}</p><p><strong>Status:</strong> {Object.entries(summary.statusCounts).map(([key,value])=>`${key} ${value}`).join(" / ")}</p><p><strong>RF / Communication:</strong> {Object.entries(summary.typeResults).map(([key,value])=>`${key} ${Object.values(value).reduce((a,b)=>a+b,0)}`).join(" / ")}</p><p><strong>Context:</strong> {Object.entries(summary.technicalContext).map(([key,value])=>`${key} ${value}`).join(" / ")} / UAS_SPECIFIC {summary.uasSpecificCount}</p><p><strong>Visual / Table:</strong> {summary.visualStatus} / {summary.tableStatus} / Regulatory lineage {summary.regulatoryLineageCount}</p><p><strong>Gap / Candidate:</strong> {summary.gapCount} / {summary.canonicalCandidateCount}</p><p><strong>Runtime / TS:</strong> {summary.runtimeReadiness} / {summary.tsStatus}</p><p>Canonical generated {String(summary.canonicalGenerated)} / Canonical ID issued {summary.canonicalIdIssued} / Unsupported inference {summary.unsupportedInferenceCount} / Mutation {Object.values(summary.mutations).reduce((a,b)=>a+b,0)}</p></section>}

async function loadIngestionSummary() {
  try {
    return JSON.parse(await readFile(join(process.cwd(), "work/source-ingestion/source-batch-001/runs/ingestion-summary.json"), "utf8")) as IngestionSummary;
  } catch { return null; }
}

async function loadAnnexSummary() { return loadJson<AnnexIngestionSummary | null>("work/source-ingestion/source-batch-002/ingestion-summary.json", null); }
async function loadJson<T>(path: string, fallback: T): Promise<T> { try { return JSON.parse(await readFile(join(process.cwd(), path), "utf8")) as T; } catch { return fallback; } }

export type IngestionSummary = { sourcesProcessed:number; readyJobsExecuted:number; jobStatus:Record<string,number>; pagesProcessed:number; articlesExtracted:number; paragraphsExtracted:number; itemsExtracted:number; tablesDetected:number; tablesExtracted:number; factCandidatesGenerated:number; relationCandidatesGenerated:number; conflictsDetected:number; revisionComparison:Record<string,number>; averageExtractionQuality:number; sourceQuality:Array<{sourceId:string;extractionQualityScore:number;htmlPdfAgreementRate:number;tableExtractionRate:number;unresolvedReferenceRate:number}>; packMutationCount:number };
export type AnnexIngestionSummary = { attachmentsDiscovered:number;attachmentsDownloaded:number;annexes:number;forms:number;tablesExtracted:number;tableFactCandidates:number;relationCandidates:number;referencesEvaluated:number;referenceStatus:Record<string,number>;blockedJobsBefore:number;blockedJobsAfter:number;examRelevance:Record<string,number>;conflicts:number;manualAcquisitionRequired:number;qualityMetrics:Record<string,number>;status:string;packMutationCount:number;factMutationCount:number;graphMutationCount:number;warnings:string[] };
export type AttachmentRecord = { attachmentId:string;title:string;attachmentType:string;officialPageUrl:string;localPath?:string;validationStatus:string;versionStatus:string };
export type PrecisionIngestionSummary = { attachmentsDiscovered:number;attachmentsDownloaded:number;attachmentsByParent:Record<string,number>;referencesEvaluated:number;referenceStatus:Record<string,number>;blockedJobsBefore:number;blockedJobsAfter:number;blockedJobStatus:Record<string,string>;precisionTables:number;precisionCandidates:number;examRelevance:Record<string,number>;visualExceptions:number;qualityMetrics:Record<string,number>;status:string;packMutationCount:number;factMutationCount:number;graphMutationCount:number };
export type TableValidationSummary = { scopeTables:number;officialRenderedPages:number;visualExceptionsBefore:number;visualExceptionsAfter:number;detectedFootnotes:number;resolvedFootnotes:number;highCandidates:number;validatedHighCandidates:number;reviewRequiredHighCandidates:number;rejectedHighCandidates:number;manualReviewTables:number;tableLayerStatus:string;mutationCount:number };
export type TableReviewItem = { tableId:string;affectedCandidateIds:string[];unresolvedRegions:string[];unresolvedFootnotes:string[];requiredHumanAction:string;severity:string };
export type LegalValidationManifest = { totalCandidateCount:number; eligibility:Record<string,number>; highRelevanceReadyCount:number; mediumRelevanceReadyCount:number; batchCount:number; tableLayerStatus:string; mutationCount:number };
export type LegalValidationBatch = { batchId:string;topic:string;candidateCount:number;eligibleCount:number;eligibleWithWarningsCount:number;blockedCount:number;highRelevanceCount:number;mediumRelevanceCount:number;status:string };
export type LegalValidationBatchSummary = { batchId:string;topic:string;inputCandidateCount:number;status:string;validationStatus:Record<string,number>;checksum:string };
export type LegalValidationSummary = { inputCandidateCount:number;executedCandidateCount:number;preBlockedCandidateCount:number;preBlockedStatus:Record<string,number>;batchCount:number;batchSummaries:LegalValidationBatchSummary[];validationStatus:Record<string,number>;blockerTypes:Record<string,number>;canonicalDuplicateGroupCount:number;conflictResultCount:number;revisionAssessmentCount:number;legalKnowledgeSetCandidateCount:number;topicCoverage:Record<string,number>;tableLayerStatus:string;mutationCount:number };
export type LegalTopicCoverage = { topicId:string;topicLabel:string;validatedCandidateCount:number;validatedHighCount:number;validatedMediumCount:number;blockedCount:number;conflictCount:number;duplicateCount:number;currentOfficialSourceCount:number;sourceDiversity:number;coverageConfidence:number;status:string };
export type LegalConsolidationSummary = { inputCandidateCount:number;ruleClusterCount:number;canonicalUnitCount:number;consolidationRatio:number;exactMergeCount:number;crossSourceMergeCount:number;parentChildMergeCount:number;compositeUnitCount:number;archiveOnlyCount:number;conflictBlockedCount:number;warningInputCount:number;canonicalStatus:Record<string,number>;topicStatus:Record<string,number>;gapTopicCount:number;legacyMigration:Record<string,number>;canonicalSetChecksum:string;mutationCount:number };
export type CanonicalTopicCoverage = { topicId:string;topicLabel:string;rawCandidateCount:number;validatedCandidateCount:number;canonicalUnitCount:number;canonicalHighCount:number;canonicalMediumCount:number;compositeUnitCount:number;conflictBlockedCount:number;archiveOnlyCount:number;sourceDiversity:number;coverageConfidence:number;status:string };
export type TopicGap = { topicId:string;topicLabel:string;reasons:string[];canonicalUnitCount:number;recommendedAction:string };
export type ShadowRuntimeSummary = { inputCanonicalUnits:number;shadowFactCount:number;compatibilitySummary:Record<string,number>;questionEligible:number;classicGenerated:number;graphGenerated:number;quality:{averageScore:number;uniquenessFailures:number;duplicateDistractors:number;unsafeDistractors:number;sourceTraceFailures:number};semanticDuplicates:number;topicRuntimeStatus:Record<string,number>;yield:{generationSuccessRate:number;usableKnowledgeRate:number};templateGaps:Array<{missingQuestionType:string;affectedKnowledgeCount:number;priority:string}>;status:string;mutationCount:number };
export type RuntimeHardeningSummary={attempts:number;success:number;failures:number;templateDistribution:Record<string,number>;supportedTemplateCount:number;stemRepetition:number;graphUsageScore:number;graphBackedQuestions:number;performance:{compileMs:number;baselineClassicMs:number;improvementRate:number;peakMemoryMb:number};status:string;mutationCount:number};
export type WeatherSourceSummary={discoveredSources:number;acquiredSources:number;currentSources:number;possiblyOutdatedSources:number;weatherTopicCount:number;coveredTopics:number;visualAssets:number;visualAssetTypes:string[];readyIngestionJobs:number;manualAcquisitionRequired:number;legalMutationCount:number};
export type WeatherBatchSummary={batchId:string;name:string;totalTopics:number;sourceCoveredTopics:number;ingestedTopics:number;knowledgeAvailableTopics:number;gapTopics:number;readySourceCount:number;status:string};
export type WeatherIngestionSummary={attemptedReadySources:number;completedSources:number;failedSources:number;pagesProcessed:number;sectionsProcessed:number;concepts:number;phenomena:number;hazards:number;observations:number;weatherCodes:number;operationalImpacts:number;relationships:number;visualLinks:number;validationReadyKnowledge:number;manualAcquisitionRequired:number;new003DSources:number;new003FSources:number;droneSpecificSourceStatus:string;legalMutationCount:number};
export type WeatherIngestionBatch={batchId:string;name:string;totalTopics:number;sourceCoveredTopics:number;ingestedTopics:number;knowledgeAvailableTopics:number;gapTopics:number;readySourceCount:number;status:string};
export type WeatherReconciliationSummary={knowledge:number;baseline:number;added:number;newSources:number;provenance:Record<string,number>;eligibility:Record<string,number>;validation:Record<string,number>;canonical:Record<string,number>;weatherCodes:Record<string,number>;operationalImpacts:Record<string,number>;relationships:Record<string,number>};
export type WeatherRecoverySummary={weatherCodeBaseline:number;weatherCodeValidation:Record<string,number>;batch003E:string;observationGuideline:string;officialSourcesDiscovered:number;officialSourcesAcquired:number;directDroneSources:number;operationalImpactValidation:Record<string,number>;droneSpecificImpacts:number;batch003F:string;canonicalV2Total:number;canonicalV2Counts:Record<string,number>;shadowRuntimeReadiness:string};
export type WeatherHazardObservationRecoverySummary={hazardBaseline:number;hazardRecovered:number;hazardValidation:Record<string,number>;observationBaseline:number;observationRecovered:number;observationValidation:Record<string,number>;newRelations:number;observationGuideline:string;canonicalV3Total:number;canonicalV3Counts:Record<string,number>;canonicalV3Checksum:string;coverage:{definedTopics:number;sourceConnectedTopics:number;validatedKnowledgeTopics:number;hazardCoverage:number;observationCoverage:number;weatherCodeCoverage:number;operationalImpactCoverage:number};batches:Record<string,string>;shadowRuntimeReadiness:string};
export type WeatherShadowRuntimeSummary={canonicalInput:number;compatibility:Record<string,number>;questionEligible:number;compilerCompatible:number;classic:{attempted:number;generated:number;skipped:number;failed:number};graph:{nodes:number;relations:number;usableUnits:number;graphBackedQuestions:number;graphBackedDistractors:number;graphUsageScore:number};questionTypes:Record<string,number>;knowledgeTypeYield:Record<string,{canonical:number;eligible:number;generated:number}>;quality:Record<string,number>;topicRuntime:Record<string,number>;templateGaps:number;status:string;mutationCount:number};
export type FlightTheorySourceSummary={institutionsInvestigated:number;sourcesDiscovered:number;sourcesAcquired:number;currentOrStableSources:number;totalTopics:number;sourceConnectedTopics:number;readyTopics:number;visualAssets:number;visualTypes:string[];formulas:number;procedures:number;readyJobs:number;manualAcquisition:number;batchCoverage:Array<{batchId:string;topicCount:number;sourceCoveredTopics:number;missingTopics:number;sourceCount:number;officialSourceCount:number;visualAssetCount:number;formulaCount:number;procedureCount:number;status:string}>;majorGaps:Record<string,number>;legalRuntime:string;weatherRuntime:string;flightTheory:string;mutationCount:number};
export type FlightTheoryCdeSummary={sourcesDiscovered:number;sourcesAcquired:number;domesticOfficialSources:number;overseasOfficialSources:number;visualAssets:number;formulas:number;tables:number;manualAcquisition:number;vendorOnlyBlocked:number;readyJobs:number;partialJobs:number;topicCoverage:Record<string,{batchId:string;totalTopics:number;sourceCovered:number;localReady:number;domesticReady:number;uasSpecificReady:number;generalTechnicalOnly:number;manualRequired:number;missing:number;status:string}>;gapCounts:Record<string,number>;canonicalBaseline:{total:number};mutations:Record<string,number>};
export type FlightTheory004CSummary={sourcesUsed:string[];pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;conceptsGenerated:number;propulsionComponentsGenerated:number;batteryKnowledgeGenerated:number;safetyKnowledgeGenerated:number;formulasGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;tableCandidates:number;technicalContext:Record<string,number>;validationEligibility:Record<string,number>;remainingGaps:string[];tsRecoveryStatus:string;batch004DStatus:string;batch004EStatus:string;unsupportedInferenceCount:number;canonicalBaseline:number;mutationCount:number;status:string};
export type FlightTheory004CValidationSummary={rawInputCount:number;knowledgeValidationInputCount:number;visualValidationInputCount:number;tableValidationInputCount:number;knowledgeStatus:Record<string,number>;typeResults:Record<string,Record<string,number>>;formulaResults:Record<string,number>;visualResults:Record<string,number>;tableResults:Record<string,number>;technicalContext:Record<string,number>;canonicalCandidateCount:number;canonicalCandidateStatus:Record<string,number>;gapCount:number;gaps:string[];cRateValidated:boolean;lipoGapPreserved:boolean;unsupportedInferenceCount:number;runtimeReadiness:string;tsRecoveryStatus:string;canonicalBaseline:number;canonicalGenerated:boolean;mutations:Record<string,number>};
export type FlightTheory004CCanonicalSummary={canonicalInput:number;canonicalGenerated:number;canonicalUnits:number;relationshipUnits:number;typeDistribution:Record<string,number>;candidateStatus:Record<string,number>;technicalContext:Record<string,number>;formulaCount:number;relationshipCount:number;visualSupportCount:number;visualCanonicalCount:number;unresolvedTableCount:number;tableCanonicalCount:number;gapCount:number;gaps:string[];runtimeReadiness:string;freezeStatus:string;existingCanonicalBaseline:number;totalFlightTheoryCanonical:number;tsRecoveryStatus:string;nextBatch:string;checksum:string;checksumReproducible:boolean;mutations:Record<string,number>};
export type FlightTheory004DSummary={sourcesUsed:string[];pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;controlConceptsGenerated:number;sensorComponentsGenerated:number;sensorPrinciplesGenerated:number;navigationKnowledgeGenerated:number;failureKnowledgeGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;tableCandidates:number;formulasGenerated:number;technicalContext:Record<string,number>;validationEligibility:Record<string,number>;validationInputCount:number;remainingGaps:string[];tsRecoveryStatus:string;batch004EStatus:string;unsupportedInferenceCount:number;canonicalBaseline:number;mutationCount:number;status:string};
export type FlightTheory004DValidationSummary={primaryKnowledgeCount:number;visualCount:number;tableCount:number;statusCounts:Record<string,number>;typeResults:Record<string,Record<string,number>>;visualStatus:string;tableStatus:string;technicalContext:Record<string,number>;uasSpecificCount:number;canonicalCandidateCount:number;canonicalCandidateStatus:Record<string,number>;gapCount:number;topicStatusCounts:Record<string,number>;runtimeReadiness:string;tsStatus:string;batch004EStatus:string;unsupportedInferenceCount:number;canonicalGenerated:boolean;canonicalIdIssued:number;canonicalBaseline:number;mutations:Record<string,number>};
export type FlightTheory004DCanonicalSummary={canonicalInput:number;canonicalGenerated:number;canonicalUnits:number;relationshipUnits:number;typeDistribution:Record<string,number>;candidateStatus:Record<string,number>;technicalContext:Record<string,number>;uasSpecificCount:number;visualSupportCount:number;visualCanonicalCount:number;unresolvedTableCount:number;tableCanonicalCount:number;formulaCount:number;gapCount:number;topicStatusCounts:Record<string,number>;runtimeReadiness:string;freezeStatus:string;totalFlightTheoryCanonical:number;tsStatus:string;nextBatch:string;checksum:string;checksumReproducible:boolean;mutations:Record<string,number>};
export type FlightTheory004ESummary={sourcesUsed:string[];pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;rfConceptsGenerated:number;communicationComponentsGenerated:number;communicationLinksGenerated:number;interferenceKnowledgeGenerated:number;failureKnowledgeGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;tableCandidates:number;formulasGenerated:number;technicalContext:Record<string,number>;uasSpecificCount:number;regulatoryLineageCount:number;validationEligibility:Record<string,number>;validationInputCount:number;remainingGaps:string[];tsStatus:string;unsupportedInferenceCount:number;canonicalBaseline:number;canonicalGenerated:boolean;mutationCount:number;status:string};
export type FlightTheory004EValidationSummary={primaryKnowledgeCount:number;visualCount:number;tableCount:number;statusCounts:Record<string,number>;typeResults:Record<string,Record<string,number>>;failureKnowledgeCount:number;visualStatus:string;tableStatus:string;technicalContext:Record<string,number>;uasSpecificCount:number;regulatoryLineageCount:number;canonicalCandidateCount:number;canonicalCandidateStatus:Record<string,number>;gapCount:number;topicStatusCounts:Record<string,number>;runtimeReadiness:string;tsStatus:string;unsupportedInferenceCount:number;canonicalGenerated:boolean;canonicalIdIssued:number;canonicalBaseline:number;mutations:Record<string,number>};
export type FlightTheory004ASummary={sourcesProcessed:number;pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;conceptsGenerated:number;principlesGenerated:number;formulasGenerated:number;formulaStatus:Record<string,number>;relationshipsGenerated:number;visualLinksGenerated:number;quality:Record<string,number>;validationEligibility:Record<string,number>;blockedItems:number;status:string;mutationCount:number};
export type FlightTheory004AValidationSummary={input:Record<string,number>;status:Record<string,number>;byType:Record<string,Record<string,number>>;canonical:{total:number;concepts:number;principles:number;formulas:number;relationships:number;checksum:string};topicCoverage:Record<string,number>;readiness:string;mutationCount:number};
export type FlightTheory004BSummary={sourcesProcessed:number;pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;componentsGenerated:number;systemsGenerated:number;conceptsGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;quality:Record<string,number>;validationReadyCount:number;validationStatus:string;unsupportedInferenceCount:number;status:string;mutationCount:number};
export type FlightTheory004BValidationSummary={input:Record<string,number>;status:Record<string,number>;byType:Record<string,Record<string,number>>;canonical:{total:number;components:number;systems:number;concepts:number;relationships:number;checksum:string};topicCoverage:Record<string,number>;multicopterGap:Array<{topicId:string;status:string;gaps:string[]}>;readiness:string;mutationCount:number};
export type FlightTheory004FSummary={sourcesProcessed:number;pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;proceduresGenerated:number;orderedProcedures:number;unorderedProcedures:number;checklistItemsGenerated:number;conceptsGenerated:number;safetyKnowledgeGenerated:number;operationalDecisionsGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;procedureInventoryClassification:Record<string,number>;deferredKnowledge:Record<string,number>;unsupportedInferenceCount:number;quality:Record<string,number>;validationEligibility:Record<string,number>;validationReadyCount:number;status:string;mutationCount:number};
export type FlightTheory004FValidationSummary={inputCount:number;statusCounts:Record<string,number>;typeCounts:Record<string,number>;canonicalCount:number;canonicalTypeCounts:Record<string,number>;duplicateLoserCount:number;topicStatusCounts:Record<string,number>;deferredCounts:Record<string,number>;runtimeReadiness:string;checksum:string;mutationCount:number};
export type FlightTheory004GSummary={sourcesProcessed:number;pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;failureModesGenerated:number;failureSymptomsGenerated:number;emergencyProceduresGenerated:number;orderedProcedures:number;unorderedProcedures:number;emergencyDecisionsGenerated:number;safetyKnowledgeGenerated:number;flightConceptsGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;deferred004FRecovered:number;deferred004H:number;procedureInventoryClassification:Record<string,number>;unsupportedInferenceCount:number;quality:Record<string,number>;validationEligibility:Record<string,number>;validationReadyCount:number;status:string;mutationCount:number};
export type FlightTheory004GCanonicalSummary={inputCandidates:number;canonicalCount:number;readyCandidates:number;warningCanonical:number;excludedCount:number;typeDistribution:Record<string,number>;noKnowledgeTopics:number;runtimeReadiness:string;freezeStatus:string;deferred004H:number;checksum:string;mutationCount:number};
export type FlightTheory004HSummary={sourcesProcessed:number;sourceRegistryReady:number;pagesProcessed:number;sectionsProcessed:number;topicsProcessed:number;topicCoverage:Record<string,number>;humanFactorsGenerated:number;riskManagementGenerated:number;crewCoordinationGenerated:number;maintenanceGenerated:number;inspectionGenerated:number;safetyKnowledgeGenerated:number;flightConceptsGenerated:number;relationshipsGenerated:number;visualLinksGenerated:number;deferred004FRecovered:number;inventory004HCandidates:number;procedureInventoryFinalClassification:Record<string,number>;deferredCDE:number;unsupportedInferenceCount:number;validationEligibility:Record<string,number>;validationReadyCount:number;status:string;mutationCount:number};
export type FlightTheory004HValidationSummary={inputCount:number;statusCounts:Record<string,number>;typeResults:Record<string,Record<string,number>>;canonicalCount:number;canonicalTypeCounts:Record<string,number>;blockedCount:number;warningCount:number;topicStatusCounts:Record<string,number>;runtimeReadiness:string;freezeStatus:string;totalFlightTheoryCanonical:number;sourceGapBatches:string[];checksum:string;mutationCount:number};
