export type FlightKnowledgeType="CONCEPT"|"PRINCIPLE"|"COMPONENT"|"SYSTEM"|"FORMULA"|"PROCEDURE"|"FAILURE_MODE"|"SAFETY_RULE"|"OPERATIONAL_GUIDANCE"|"RELATIONSHIP";
export type FlightTheoryTopic={topicId:string;batchId:`004${"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"}`;parentTopicId?:string;title:string;aliases:string[];description:string;officiallyVerified:boolean;expectedKnowledgeTypes:FlightKnowledgeType[];expectedVisualTypes:string[];sourceIds:string[];priority:"P0"|"P1"|"P2"};
const groups={
 "004A":["four-forces","newton-laws","bernoulli-principle","pressure-difference","relative-wind","angle-of-attack","lift-coefficient","drag-coefficient","stall","critical-angle","induced-drag","parasite-drag","speed-and-lift","density-performance","weight-performance","stability","controllability","center-of-gravity","moment","rotational-motion","climb-descent","turn","hover"],
 "004B":["multicopter","fixed-wing","rotorcraft","helicopter","unmanned-airship","vtol","frame","arm","landing-gear","fuselage","wing","rotor","main-rotor","tail-rotor","propeller","rotor-direction","attitude-control","pitch","roll","yaw","throttle","differential-thrust","coaxial-quad-hexa-octa"],
 "004C":["voltage","current","resistance","power","ohms-law","series-circuit","parallel-circuit","motor","bldc","kv","esc","propeller-pitch","propeller-diameter","battery","lipo","cell","c-rate","capacity","charging","discharging","overcharge","overdischarge","cell-balancing","battery-storage","battery-fire","power-system","electrical-safety"],
 "004D":["flight-controller","imu","gyroscope","accelerometer","magnetometer","barometer","gps","gnss","satellite-navigation","position-hold","altitude-hold","attitude-estimation","sensor-fusion","compass","home-point","return-to-home","geofencing","vision-sensor","ultrasonic-sensor","obstacle-detection","calibration","sensor-error","gps-error","compass-error"],
 "004E":["controller","transmitter","receiver","rf-communication","frequency","antenna","los-communication","signal-attenuation","interference","link-loss","control-link","data-link","telemetry","fpv","video-transmission","failsafe","communication-range","radio-shadow","spectrum-safety"],
 "004F":["preflight-airframe","preflight-propeller","preflight-motor","preflight-battery","preflight-controller","preflight-gps-sensor","preflight-home-point","preflight-area-obstacle","preflight-weather-link","flight-plan","inflight-attitude-altitude-distance","inflight-battery-signal","inflight-traffic-obstacle","inflight-vibration-noise","inflight-weather-change","return-decision","postflight-power-off","postflight-inspection","postflight-battery-damage","flight-record","maintenance-decision","storage"],
 "004G":["emergency-link-loss","emergency-gps-error","emergency-compass-error","motor-failure","esc-failure","propeller-damage","low-battery","battery-abnormal","aircraft-abnormal","flyaway","rth-error","abnormal-vibration","forced-landing","emergency-landing","collision-risk","people-facility-approach","accident-prevention","post-accident-response","battery-fire-response","aircraft-fire"],
 "004H":["human-factors","situational-awareness","fatigue","stress","attention","decision-making","human-error","communication","crm","team-coordination","risk-assessment","hazard-identification","risk-mitigation","checklist","sop","maintenance","preventive-maintenance","inspection-cycle","records-management","parts-replacement","safety-culture"]
} as const;
export const DRONE_FLIGHT_THEORY_OPERATION_TAXONOMY:FlightTheoryTopic[]=Object.entries(groups).flatMap(([batch,topics])=>topics.map((title)=>({topicId:`flight:${title}`,batchId:batch as FlightTheoryTopic["batchId"],title,aliases:[],description:title,officiallyVerified:false,expectedKnowledgeTypes:(batch==="004F"?["PROCEDURE","OPERATIONAL_GUIDANCE"]:batch==="004G"?["FAILURE_MODE","SAFETY_RULE"]:batch==="004H"?["SAFETY_RULE","PROCEDURE"]:["CONCEPT","PRINCIPLE","RELATIONSHIP"]) as FlightKnowledgeType[],expectedVisualTypes:["DIAGRAM"],sourceIds:[],priority:"P1"})));
