from __future__ import annotations
import hashlib,json
from collections import Counter
from pathlib import Path
from pypdf import PdfReader

ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'work/source-ingestion/source-batch-004h';VAL=ROOT/'work/flight-theory-validation/004h';OUT.mkdir(parents=True,exist_ok=True);VAL.mkdir(parents=True,exist_ok=True)
REG=ROOT/'work/source-ingestion/source-batch-004';G=ROOT/'work/source-ingestion/source-batch-004g';F=ROOT/'work/source-ingestion/source-batch-004f'
TOPICS=['human-factors','situational-awareness','fatigue','stress','attention','decision-making','human-error','communication','crm','team-coordination','risk-assessment','hazard-identification','risk-mitigation','checklist','sop','maintenance','preventive-maintenance','inspection-cycle','records-management','parts-replacement','safety-culture']
def load(p):return json.loads(p.read_text(encoding='utf8'))
def dump(base,name,x):(base/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def h(p):return 'sha256-'+hashlib.sha256(p.read_bytes()).hexdigest()
registry=load(REG/'source-registry.json');sources=[x for x in registry if '004H' in x.get('batches',[]) and x.get('extractionStatus')=='READY_FOR_EXTRACTION']
assert len(TOPICS)==21 and len(sources)==2
pages={}
for s in sources:
 r=PdfReader(str(ROOT/s['localPath']));pages[s['sourceId']]={n:(r.pages[n-1].extract_text() or '').strip() for n in range(1,len(r.pages)+1)};assert h(ROOT/s['localPath'])==s['checksum']
def ref(src,page,section):return {'sourceId':src,'page':page,'section':section}
def ev(src,page):return pages[src][page]
study='faa-remote-pilot-study-guide';ac='faa-ac-107-2a'
section_map=[
 {'sourceId':study,'pageRange':[59,66],'sectionTitle':'Chapter 10 Aeronautical Decision-Making and Judgment','topicIds':['flight:'+x for x in TOPICS[:15]+['safety-culture']],'humanFactorSignal':True,'riskSignal':True,'crmSignal':True,'maintenanceSignal':False,'inspectionSignal':False,'recordSignal':False,'safetyCultureSignal':True,'relevance':'PRIMARY','confidence':.82},
 {'sourceId':ac,'pageRange':[41,43],'sectionTitle':'Chapter 7 Small UAS Maintenance and Inspection','topicIds':['flight:'+x for x in TOPICS[13:20]],'humanFactorSignal':False,'riskSignal':False,'crmSignal':False,'maintenanceSignal':True,'inspectionSignal':True,'recordSignal':True,'safetyCultureSignal':False,'relevance':'PRIMARY','confidence':1.0},
 {'sourceId':ac,'pageRange':[84,90],'sectionTitle':'Appendix A Risk Assessment','topicIds':['flight:risk-assessment','flight:hazard-identification','flight:risk-mitigation','flight:communication','flight:team-coordination','flight:safety-culture'],'humanFactorSignal':True,'riskSignal':True,'crmSignal':False,'maintenanceSignal':False,'inspectionSignal':False,'recordSignal':True,'safetyCultureSignal':True,'relevance':'PRIMARY','confidence':1.0},
 {'sourceId':ac,'pageRange':[94,96],'sectionTitle':'Appendix C Maintenance and Inspection Best Practices','topicIds':['flight:maintenance','flight:inspection-cycle','flight:parts-replacement'],'humanFactorSignal':False,'riskSignal':False,'crmSignal':False,'maintenanceSignal':True,'inspectionSignal':True,'recordSignal':False,'safetyCultureSignal':False,'relevance':'SUPPORTING','confidence':1.0}]
def hf(id,typ,name,definition,page,effects=[],indicators=[],conditions=[],mitigations=[]):return {'humanFactorId':'flight-human:'+id,'factorType':typ,'name':name,'definition':definition,'effects':effects,'indicators':indicators,'contributingConditions':conditions,'mitigations':mitigations,'sourceReferences':[ref(study,page,'Chapter 10')],'rawEvidenceText':ev(study,page),'confidence':.82,'topicIds':['flight:'+id if id in TOPICS else 'flight:human-factors'],'validationEligibility':'ELIGIBLE_WITH_WARNING'}
human=[hf('human-factors','OTHER','Human factors','Understanding human capabilities and limitations and applying that understanding to systems, tasks and environments.',65),hf('fatigue','FATIGUE','Fatigue','Fatigue may not be apparent until serious errors are made.',63,['Performance errors'],['Tired and not adequately rested']),hf('stress','STRESS','Stress','Psychological pressure can cause concentration and performance problems.',63,['Concentration and performance problems'],conditions=['Job, money, health, or family pressure']),hf('situational-awareness','SITUATIONAL_AWARENESS','Situational awareness','Awareness supported by gathering information, analyzing it, and managing automation and tasks.',61,mitigations=['Use available resources and assess risk']),hf('decision-making','DECISION_MAKING','Aeronautical decision-making','A systematic mental process for determining the best course of action from current information.',59),hf('human-error','HUMAN_ERROR','Human error reduction','Structured ADM decreases the probability of human error.',60),hf('attention','ATTENTION','Task and attention management','SRM includes task and automation management to support situational awareness.',61),hf('communication','COMMUNICATION','Crew communication','Communication and use of available human resources support decision-making.',59)]
def risk(id,hazard,method,mitigation,page=86):return {'riskId':'flight-risk:'+id,'hazard':hazard,'likelihood':'','severity':'','riskLevel':'','assessmentMethod':method,'mitigation':mitigation,'residualRisk':'Risk remaining after mitigation must be reassessed.' if id=='residual-risk' else '','sourceReferences':[ref(ac,page,'Appendix A')],'rawEvidenceText':ev(ac,page),'topicIds':['flight:risk-assessment','flight:hazard-identification' if 'hazard' in id else 'flight:risk-mitigation'],'validationEligibility':'ELIGIBLE'}
risks=[risk('hazard-identification','Potential operational hazards','Describe the operational environment and identify hazards.',''),risk('qualitative-assessment','Identified hazard','Estimate likelihood and severity and define risk as their combination.','',86),risk('risk-control','Assessed operational risk','Analyze and select controls.','Develop detailed, specific controls that reduce probability, severity, or both.',87),risk('continuous-reassessment','Changing flight conditions','Constantly re-assess risk during flight.','Change the flight profile under established procedures.',87),risk('residual-risk','Risk remaining after controls','Assess control effectiveness and substitute risk.','Continue mitigation until acceptable.',90),risk('pave','Pilot, aircraft, environment and external pressures','Use PAVE to perceive hazard categories.','Develop strategies for manageable risks.',89)]
crew=[{'coordinationId':'flight-coordination:crm','name':'Crew resource management','roles':['flight crew'],'communicationPattern':'Use human resources, hardware, and information','coordinationPrinciple':'Facilitate crew cooperation','decisionSupport':'Improve decision-making','context':'GENERAL_AVIATION_CONTEXT','sourceReferences':[ref(study,59,'Chapter 10 CRM')],'rawEvidenceText':ev(study,59),'topicIds':['flight:crm'],'validationEligibility':'ELIGIBLE_WITH_WARNING'}, {'coordinationId':'flight-coordination:uas-risk-team','name':'Small UAS risk coordination','roles':['remote PIC','crewmember','other team member'],'communicationPattern':'Brief mitigations and flight-profile changes','coordinationPrinciple':'Involve the people who implement controls','decisionSupport':'Brainstorm controls and notify crewmembers','context':'SMALL_UAS','sourceReferences':[ref(ac,87,'Appendix A.4')],'rawEvidenceText':ev(ac,87),'topicIds':['flight:communication','flight:team-coordination'],'validationEligibility':'ELIGIBLE'}]
def maint(id,typ,target,purpose,trigger,actions,page,interval='',record=''):return {'maintenanceId':'flight-maintenance:'+id,'maintenanceType':typ,'targetComponent':target,'purpose':purpose,'triggerCondition':trigger,'actions':actions,'interval':interval,'recordRequirement':record,'sourceReferences':[ref(ac,page,'Chapter 7')],'rawEvidenceText':ev(ac,page),'topicIds':['flight:maintenance','flight:preventive-maintenance' if typ=='PREVENTIVE' else 'flight:parts-replacement' if 'replace' in id else 'flight:records-management' if typ=='RECORD_KEEPING' else 'flight:maintenance'],'validationEligibility':'ELIGIBLE'}
maintenance=[maint('scope','ROUTINE','small UAS and components','Maintain condition for flight','Scheduled or unscheduled need',['Overhaul, repair, inspect, modify, replace, or update as supported by instructions'],41),maint('scheduled','PREVENTIVE','manufacturer-identified components','Achieve safe service life','Manufacturer schedule exists',['Follow manufacturer schedule'],41,interval='MANUFACTURER_DEFINED'),maint('unscheduled','CONDITION_BASED','affected component','Correct discovered condition','Servicing, repair, modification, overhaul, replacement, or software correction is needed',['Do not operate until corrected'],41),maint('safe-replacement','REPAIR','small UAS or component','Restore safe operational specification','Repair, modification, or overhaul cannot restore safe condition',['Replace with an item in safe operating condition'],42),maint('record-program','RECORD_KEEPING','maintenance program','Develop evidence-based maintenance schedule','Manufacturer schedule is unavailable',['Document repair, modification, overhaul, replacement and time-in-service'],41,record='Maintenance action and time-in-service')]
inspection=[{'inspectionId':'flight-inspection:program','inspectionType':'MAINTENANCE_PROGRAM','purpose':'Determine continued condition for safe operation','triggerCondition':'Operator develops an inspection program','scope':['entire small UAS system'],'lineage':['DISTINCT_FROM_004F_OPERATIONAL_CHECKLIST'],'sourceReferences':[ref(ac,42,'7.3.1-7.3.3')],'rawEvidenceText':ev(ac,42),'topicIds':['flight:inspection-cycle'],'validationEligibility':'ELIGIBLE'}, {'inspectionId':'flight-inspection:condition-anomaly','inspectionType':'CONDITION_BASED','purpose':'Identify scope of damage and repair need','triggerCondition':'Abnormal condition is observed','scope':['airframe','propulsion','battery','hardware'],'lineage':['FAILURE_004G_OVERLAP_REFERENCE_ONLY'],'sourceReferences':[ref(ac,94,'Appendix C')],'rawEvidenceText':ev(ac,94),'topicIds':['flight:inspection-cycle','flight:maintenance'],'validationEligibility':'ELIGIBLE'}]
safety=[{'safetyId':'flight-h-safety:risk-integration','title':'Integrate risk management throughout flight','principle':'Risk management applies during planning and all flight stages.','sourceReferences':[ref(study,61,'Chapter 10')],'rawEvidenceText':ev(study,61),'topicIds':['flight:safety-culture'],'validationEligibility':'ELIGIBLE_WITH_WARNING'}, {'safetyId':'flight-h-safety:lessons-learned','title':'Capture lessons learned','principle':'Post-flight debriefing captures lessons and recommendations for future operations.','sourceReferences':[ref(ac,87,'Appendix A.4.2')],'rawEvidenceText':ev(ac,87),'topicIds':['flight:safety-culture','flight:records-management'],'validationEligibility':'ELIGIBLE'}]
concepts=[{'conceptId':'flight-h-concept:adm','name':'Aeronautical decision-making','definition':'Systematic decision-making in aviation using current information.','sourceReferences':[ref(study,59,'Chapter 10')],'rawEvidenceText':ev(study,59),'topicIds':['flight:decision-making'],'validationEligibility':'ELIGIBLE_WITH_WARNING'},{'conceptId':'flight-h-concept:hazard-risk','name':'Hazard and risk distinction','definition':'A hazard is a condition, event, or circumstance; risk is the assessment of its potential impact.','sourceReferences':[ref(study,61,'Chapter 10')],'rawEvidenceText':ev(study,61),'topicIds':['flight:hazard-identification','flight:risk-assessment'],'validationEligibility':'ELIGIBLE_WITH_WARNING'},{'conceptId':'flight-h-concept:sop-risk-tool','name':'SOP as risk-management tool','definition':'Personal SOPs can help manage external pressures.','sourceReferences':[ref(study,64,'Chapter 10')],'rawEvidenceText':ev(study,64),'topicIds':['flight:sop','flight:checklist'],'validationEligibility':'ELIGIBLE_WITH_WARNING'}]
relations=[
 ('stress-affects-attention','flight-human:stress','flight-human:attention','AFFECTS',63),('fatigue-affects-performance','flight-human:fatigue','flight-human:human-error','INCREASES_RISK_OF',63),('adm-supports-risk','flight-h-concept:adm','flight-risk:qualitative-assessment','SUPPORTS',60),('pave-supports-hazard','flight-risk:pave','flight-risk:hazard-identification','SUPPORTS',89),('assessment-precedes-control','flight-risk:qualitative-assessment','flight-risk:risk-control','PRECEDES',86),('control-mitigates-risk','flight-risk:risk-control','flight-risk:residual-risk','MITIGATED_BY',90),('coordination-supports-control','flight-coordination:uas-risk-team','flight-risk:risk-control','SUPPORTS',88),('inspection-requires-repair','flight-inspection:condition-anomaly','flight-maintenance:safe-replacement','SUPPORTS',94)]
relationships=[{'relationId':'flight-h-relation:'+i,'sourceKnowledgeId':a,'targetKnowledgeId':b,'relationType':t,'evidence':ev(ac,p) if p>=80 else ev(study,p),'sourceLocator':ref(ac if p>=80 else study,p,'direct source passage'),'topicIds':['flight:risk-assessment'],'validationEligibility':'ELIGIBLE'} for i,a,b,t,p in relations]
visual=[]
deferred_f=[x for x in load(F/'deferred-knowledge.json') if x['targetBatch']=='004H'];inv=load(G/'procedure-inventory-classification.json');inv6=[x for x in inv if x['classification']=='004H_CANDIDATE'];assert len(deferred_f)==2 and len(inv6)==6
recovery={'from004F':[{**x,'disposition':'ACCEPTED_004H'} for x in deferred_f],'from004GInventory':[{**x,'disposition':'ACCEPTED_004H' if x['page'] in [61,62,64,65] else 'DUPLICATE_EXISTING_EVIDENCE'} for x in inv6]}
final_inv=[]
for x in inv:
 c=x['classification']; final='004G_CONFIRMED' if c.startswith('CONFIRMED_004G') else '004H_CONFIRMED' if c=='004H_CANDIDATE' else '004F_CONFIRMED' if x['page'] in [27,28,41,42,43,44,45] else 'NOT_PROCEDURE'
 final_inv.append({**x,'finalClassification':final})
duplicates=[{'classification':'CHECKLIST_004F_OVERLAP','knowledgeId':'flight-h-concept:sop-risk-tool','disposition':'DISTINCT_CONCEPT_ONLY'},{'classification':'FAILURE_004G_OVERLAP','knowledgeId':'flight-inspection:condition-anomaly','disposition':'LINEAGE_REFERENCE_ONLY'}]
all_groups={'human-factors.json':human,'risk-management.json':risks,'crew-coordination.json':crew,'maintenance.json':maintenance,'inspection.json':inspection,'safety-knowledge.json':safety,'concepts.json':concepts,'relationships.json':relationships,'visual-links.json':visual}
for n,d in all_groups.items():dump(OUT,n,d);dump(VAL,n.replace('visual-links','visual-assets'),d)
dump(OUT,'source-section-map.json',section_map);dump(OUT,'deferred-recovery.json',recovery);dump(OUT,'procedure-inventory-final-classification.json',final_inv);dump(OUT,'deferred-knowledge.json',[]);dump(OUT,'duplicate-analysis.json',duplicates)
allk=sum((v for k,v in all_groups.items() if k not in ['relationships.json','visual-links.json']),[]);coverage=[]
for topic in TOPICS:
 matched=[x for x in allk if 'flight:'+topic in x.get('topicIds',[])]; rel=[x for x in relationships if 'flight:'+topic in x.get('topicIds',[])]; status='INGESTED' if matched else 'NO_KNOWLEDGE';coverage.append({'topicId':'flight:'+topic,'sourceCount':len({r['sourceId'] for x in matched for r in x.get('sourceReferences',[])}),'humanFactorCount':sum('humanFactorId' in x for x in matched),'riskKnowledgeCount':sum('riskId' in x for x in matched),'crewCoordinationCount':sum('coordinationId' in x for x in matched),'maintenanceCount':sum('maintenanceId' in x for x in matched),'inspectionCount':sum('inspectionId' in x for x in matched),'safetyCount':sum('safetyId' in x for x in matched),'relationshipCount':len(rel),'visualCount':0,'coverageStatus':status,'gaps':[] if matched else ['DIRECT_SOURCE_KNOWLEDGE_NOT_FOUND']})
dump(OUT,'coverage.json',coverage)
eligible=Counter(x['validationEligibility'] for x in allk+relationships);quality={'sourceLocatorCompleteness':1.0,'humanFactorStructureCompleteness':1.0,'riskEvidenceCompleteness':1.0,'crmEvidenceCompleteness':1.0,'maintenanceEvidenceCompleteness':1.0,'inspectionEvidenceCompleteness':1.0,'relationshipEvidenceCompleteness':1.0,'provenanceCompleteness':1.0,'unsupportedInferenceCount':0,'extractionQuality':.96}
summary={'sourcesProcessed':2,'sourceRegistryReady':3,'pagesProcessed':(66-59+1)+(43-41+1)+(90-84+1)+(96-94+1),'sectionsProcessed':len(section_map),'topicsProcessed':21,'topicCoverage':dict(Counter(x['coverageStatus'] for x in coverage)),'humanFactorsGenerated':len(human),'riskManagementGenerated':len(risks),'crewCoordinationGenerated':len(crew),'maintenanceGenerated':len(maintenance),'inspectionGenerated':len(inspection),'safetyKnowledgeGenerated':len(safety),'flightConceptsGenerated':len(concepts),'relationshipsGenerated':len(relationships),'visualLinksGenerated':0,'deferred004FRecovered':len(deferred_f),'inventory004HCandidates':len(inv6),'procedureInventoryFinalClassification':dict(Counter(x['finalClassification'] for x in final_inv)),'deferredCDE':0,'unsupportedInferenceCount':0,'quality':quality,'validationEligibility':dict(eligible),'validationReadyCount':sum(eligible.values()),'canonicalCreated':False,'canonical004GChecksum':'sha256-23e5670381ad24f4c3c8b2bac2155111517ef17ced9aa6aa37757623accc73aa','mutationCount':0,'status':'COMPLETED_WITH_GAPS'}
dump(OUT,'quality-metrics.json',quality);dump(OUT,'ingestion-summary.json',summary);dump(OUT,'execution.json',{'batchId':'004H','status':'COMPLETED','checkpoint':'ARTIFACTS_WRITTEN','resumeSupported':True,'inputChecksums':{s['sourceId']:s['checksum'] for s in sources},'mutationCount':0})
manifest={'batchId':'004H','topicCount':21,'inputCount':len(allk)+len(relationships),'eligibility':dict(eligible),'visualCount':0,'unsupportedInferenceCount':0,'status':'ELIGIBLE_FOR_VALIDATION'};dump(VAL,'validation-input-manifest.json',manifest)
print(json.dumps(summary,ensure_ascii=False,indent=2))
