from __future__ import annotations
import hashlib,json
from collections import Counter
from pathlib import Path
import pdfplumber

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'work/source-ingestion/source-batch-004g'; VALID=ROOT/'work/flight-theory-validation/004g'
BASE.mkdir(parents=True,exist_ok=True);VALID.mkdir(parents=True,exist_ok=True)
SRC=ROOT/'data/sources/drone-license/flight-theory/official/other-public/original'
AC=SRC/'faa-ac-107-2a.pdf';GUIDE=SRC/'faa-remote-pilot-study-guide.pdf'
TOPICS=['emergency-link-loss','emergency-gps-error','emergency-compass-error','motor-failure','esc-failure','propeller-damage','low-battery','battery-abnormal','aircraft-abnormal','flyaway','rth-error','abnormal-vibration','forced-landing','emergency-landing','collision-risk','people-facility-approach','accident-prevention','post-accident-response','battery-fire-response','aircraft-fire']
def dump(folder,name,value):(folder/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(path):return 'sha256-'+hashlib.sha256(path.read_bytes()).hexdigest()
def pages(path,indices):
 with pdfplumber.open(path) as pdf:return {p:(pdf.pages[p-1].extract_text() or '').strip() for p in indices}
ac=pages(AC,[33,43,46,93,94,95,96]);guide=pages(GUIDE,[43,63,66])
ref=lambda page,section:{'sourceId':'faa-ac-107-2a','page':page,'section':section}

sources=[{'sourceId':'faa-ac-107-2a','authority':'OFFICIAL_SECONDARY','currentness':'CURRENT','checksum':sha(AC),'pages':[33,43,46,93,94,95,96],'topicCoverage':TOPICS},{'sourceId':'faa-remote-pilot-study-guide','authority':'OFFICIAL_SECONDARY','currentness':'POSSIBLY_OUTDATED','checksum':sha(GUIDE),'pages':[43],'topicCoverage':['emergency-landing','accident-prevention','battery-fire-response']}]
section_map=[
 {'sourceId':'faa-ac-107-2a','pageRange':[33,33],'sectionTitle':'5.18 In-Flight Emergency','topicIds':['flight:accident-prevention','flight:people-facility-approach'],'failureSignal':False,'emergencySignal':True,'warningSignal':True,'responseSignal':True,'safetySignal':True,'relevance':'PRIMARY','confidence':1},
 {'sourceId':'faa-ac-107-2a','pageRange':[46,46],'sectionTitle':'8.3.1 Minimum Distances from a Person','topicIds':['flight:emergency-landing','flight:collision-risk','flight:people-facility-approach'],'failureSignal':True,'emergencySignal':True,'warningSignal':False,'responseSignal':False,'safetySignal':True,'relevance':'SUPPORTING','confidence':.95},
 {'sourceId':'faa-ac-107-2a','pageRange':[93,93],'sectionTitle':'Appendix B.5-B.6 Battery Fires and Frequency Utilization','topicIds':['flight:battery-fire-response','flight:aircraft-fire','flight:emergency-link-loss','flight:flyaway'],'failureSignal':True,'emergencySignal':True,'warningSignal':True,'responseSignal':True,'safetySignal':True,'relevance':'PRIMARY','confidence':1},
 {'sourceId':'faa-ac-107-2a','pageRange':[94,96],'sectionTitle':'Appendix C Table C-1 Small UAS Condition Chart','topicIds':['flight:aircraft-abnormal','flight:motor-failure','flight:propeller-damage','flight:low-battery','flight:battery-abnormal','flight:abnormal-vibration','flight:collision-risk','flight:flyaway'],'failureSignal':True,'emergencySignal':False,'warningSignal':True,'responseSignal':True,'safetySignal':True,'relevance':'PRIMARY','confidence':1},
 {'sourceId':'faa-remote-pilot-study-guide','pageRange':[43,43],'sectionTitle':'Chapter 5 Emergency Procedures','topicIds':['flight:accident-prevention','flight:battery-fire-response','flight:emergency-landing'],'failureSignal':False,'emergencySignal':True,'warningSignal':True,'responseSignal':True,'safetySignal':True,'relevance':'SUPPORTING','confidence':.75}
]
def failure(fid,name,system,ftype,page,section,topics,symptoms=None,causes=None,consequences=None,detection=None,response=None):return {'failureId':fid,'name':name,'affectedSystem':system,'affectedComponent':'','failureType':ftype,'symptoms':symptoms or [],'causes':causes or [],'consequences':consequences or [],'detection':detection or [],'response':response or [],'sourceReferences':[ref(page,section)],'rawEvidenceText':ac[page],'confidence':1,'scope':'GENERAL_UAS','topicIds':['flight:'+x for x in topics],'validationEligibility':'ELIGIBLE'}
failures=[
 failure('flight-failure:rf-interference','RF interference affecting the control link','control-link','INTERFERENCE',93,'Appendix B.6',['emergency-link-loss','flyaway'],consequences=['Loss of control or flyaway'],detection=['Control-link operation affected'],response=['Consult the operating manual and manufacturer recommended procedures; prevent obstructions within line of sight']),
 failure('flight-failure:electrical-malfunction','Possible electrical malfunction','electrical-system','MALFUNCTION',95,'Appendix C Table C-1 items 5-6',['aircraft-abnormal','aircraft-fire'],symptoms=['Electrical burning smell','Black soot tracings or sparking'],consequences=['Risk of fire or extreme heat'],detection=['Smell or visual indication'],response=['Further inspect to determine the source and assess repairs']),
 failure('flight-failure:propulsion-anomaly','Propulsion system anomaly','propulsion-system','ABNORMAL_OPERATION',95,'Appendix C Table C-1 item 7',['motor-failure','propeller-damage','abnormal-vibration'],symptoms=['Noticeable sound change during operation'],consequences=['Diminished performance'],detection=['Operational sound change'],response=['Inspect motors and propellers for damage or diminished performance']),
 failure('flight-failure:delayed-control-input','Control inputs not synchronized or delayed','control-link','CONTROL_RESPONSE_ANOMALY',95,'Appendix C Table C-1 item 8',['emergency-link-loss','collision-risk','flyaway'],symptoms=['Control inputs not synchronized or delayed'],consequences=['Possible loss of control, collision, or flyaway'],detection=['Delayed or unsynchronized control response'],response=['Discontinue flight or avoid further operations until inspection and testing establish reliable control communications']),
 failure('flight-failure:battery-distortion','Battery casing distortion','power-system','BATTERY_ABNORMAL',96,'Appendix C Table C-1 item 9',['battery-abnormal','low-battery','aircraft-fire'],symptoms=['Battery casing bulging'],consequences=['Abrupt power loss, explosion, fire, or extreme heat'],detection=['Visual casing inspection'],response=['Inspect battery integrity and assess repairs']),
 failure('flight-failure:diminishing-flight-time','Diminishing flight time capability','power-system','BATTERY_CAPACITY_ANOMALY',96,'Appendix C Table C-1 item 10',['low-battery','battery-abnormal'],symptoms=['Diminishing flight time capability'],causes=['Exhausted service life, internal damage, or external damage'],consequences=['Impending battery failure'],detection=['Observed reduction in flight time'],response=['Inspect battery integrity and assess repairs']),
 failure('flight-failure:structural-cracking','Structural or skin cracking','airframe','STRUCTURAL_DAMAGE',94,'Appendix C Table C-1 item 1',['aircraft-abnormal'],symptoms=['Structural or skin cracking'],consequences=['Hidden damage may compromise structural integrity'],detection=['Visual inspection'],response=['Inspect the scope and hidden damage and assess repairs']),
 failure('flight-failure:loose-hardware','Loose or missing hardware or fasteners','airframe','STRUCTURAL_DAMAGE',96,'Appendix C Table C-1 item 11',['aircraft-abnormal'],symptoms=['Loose or missing hardware or fasteners'],consequences=['Adverse flight characteristics, structural failure, dropped objects, or loss of aircraft'],detection=['Visual inspection'],response=['Secure loose hardware and replace hardware that cannot be secured or is missing']),
 failure('flight-failure:battery-fire','Lithium battery fire hazard','power-system','FIRE_HAZARD',93,'Appendix B.5',['battery-fire-response','aircraft-fire'],causes=['Short circuit, improper charging, extreme heat, crash damage, mishandling, or defect'],consequences=['In-flight emergency and loss of control'],response=['Follow manufacturer recommendations when available for safe battery handling and usage'])
]
symptoms=[]
for f in failures:
 for i,s in enumerate(f['symptoms'],1):symptoms.append({'symptomId':f"{f['failureId']}:symptom:{i}",'failureId':f['failureId'],'observedCondition':s,'indicator':s,'detectionContext':f['detection'][0] if f['detection'] else 'Source-described observation','sourceReference':f['sourceReferences'][0],'rawEvidenceText':f['rawEvidenceText'],'validationEligibility':'ELIGIBLE'})
procedures=[
 {'procedureId':'flight-emergency:general-response','emergencyType':'IN_FLIGHT_EMERGENCY','phase':'IN_FLIGHT','steps':['Take emergency action in a way that minimizes injury or damage to property.'],'ordered':False,'orderingEvidence':'','entryCondition':'Unexpected and unforeseen serious occurrence or situation requiring urgent, prompt action','terminationCondition':'','warnings':['Legal deviation/reporting provisions remain Legal Knowledge'],'sourceReferences':[ref(33,'5.18 In-Flight Emergency')],'rawEvidenceText':ac[33],'topicIds':['flight:accident-prevention','flight:people-facility-approach'],'validationEligibility':'ELIGIBLE'},
 {'procedureId':'flight-emergency:delayed-control-response','emergencyType':'CONTROL_LINK_ANOMALY','phase':'IN_FLIGHT','steps':['Discontinue flight and/or avoid further flight operations.','Inspect and test the control link before further flight.'],'ordered':False,'orderingEvidence':'','entryCondition':'Control inputs are not synchronized or are delayed','terminationCondition':'Accurate control communications are established and reliable','warnings':[],'sourceReferences':[ref(95,'Appendix C Table C-1 item 8')],'rawEvidenceText':ac[95],'topicIds':['flight:emergency-link-loss','flight:collision-risk','flight:flyaway'],'validationEligibility':'ELIGIBLE'}
]
decisions=[
 {'decisionId':'flight-emergency-decision:delayed-control','trigger':'Control inputs are not synchronized or are delayed','observedCondition':'Delayed or unsynchronized control response','allowedResponse':'Discontinue flight and/or avoid further flight operations until inspection and testing establish reliable control communications','prohibitedResponse':'Continue flight before reliable control communication is established','escalationCondition':'Possible loss of control, collision, or flyaway','sourceReferences':[ref(95,'Appendix C Table C-1 item 8')],'rawEvidenceText':ac[95],'topicIds':['flight:emergency-link-loss','flight:collision-risk','flight:flyaway'],'validationEligibility':'ELIGIBLE'},
 {'decisionId':'flight-emergency-decision:unsafe-condition','trigger':'Inspection identifies damage, malfunction, abnormal sound, battery distortion, or missing hardware','observedCondition':'Condition may make the small UAS unsafe for operation','allowedResponse':'Further inspect and assess the repairs needed before continued safe flight operations','prohibitedResponse':'','escalationCondition':'Repair or replacement is needed for continued safe operation','sourceReferences':[ref(94,'Appendix C Table C-1') ,ref(95,'Appendix C Table C-1'),ref(96,'Appendix C Table C-1')],'rawEvidenceText':ac[94]+'\n'+ac[95]+'\n'+ac[96],'topicIds':['flight:aircraft-abnormal','flight:abnormal-vibration','flight:battery-abnormal'],'validationEligibility':'ELIGIBLE'}
]
safety=[
 {'safetyId':'flight-emergency-safety:minimize-injury-damage','title':'Minimize injury or property damage during an in-flight emergency','hazard':'Unexpected serious occurrence requiring urgent action','preventiveAction':'','emergencyAction':'Take emergency action so as to minimize injury or damage to property','prohibitedAction':'','phase':'IN_FLIGHT','sourceReferences':[ref(33,'5.18 In-Flight Emergency')],'rawEvidenceText':ac[33],'topicIds':['flight:accident-prevention','flight:people-facility-approach'],'validationEligibility':'ELIGIBLE'},
 {'safetyId':'flight-emergency-safety:battery-fire','title':'Lithium battery fire hazard','hazard':'Lithium-based batteries are highly flammable and capable of ignition','preventiveAction':'Follow manufacturer recommendations, when available, for safe battery handling and usage','emergencyAction':'','prohibitedAction':'','phase':'ALL','sourceReferences':[ref(93,'Appendix B.5 Battery Fires')],'rawEvidenceText':ac[93],'topicIds':['flight:battery-fire-response','flight:aircraft-fire'],'validationEligibility':'ELIGIBLE_WITH_WARNING','warnings':['NO_SOURCE_SUPPORTED_FIRE_SUPPRESSION_RESPONSE']},
 {'safetyId':'flight-emergency-safety:control-link-obstruction','title':'Control-link obstruction and interference risk','hazard':'Barriers or interference may prevent the command and control link from working properly','preventiveAction':'Prevent obstructions from interfering with the line-of-sight frequency spectrum and consult manufacturer procedures','emergencyAction':'','prohibitedAction':'','phase':'ALL','sourceReferences':[ref(93,'Appendix B.6 Frequency Utilization')],'rawEvidenceText':ac[93],'topicIds':['flight:emergency-link-loss','flight:flyaway'],'validationEligibility':'ELIGIBLE'}
]
concepts=[{'conceptId':'flight-emergency-concept:in-flight-emergency','name':'In-flight emergency','definition':'An unexpected and unforeseen serious occurrence or situation requiring urgent, prompt action','sourceReferences':[ref(33,'5.18 In-Flight Emergency')],'rawEvidenceText':ac[33],'topicIds':['flight:accident-prevention'],'validationEligibility':'ELIGIBLE'},{'conceptId':'flight-emergency-concept:emergency-landing-capability','name':'Emergency landing capability','definition':'Ability to perform emergency maneuvers, including emergency landings, considered when selecting stand-off distance from people','sourceReferences':[ref(46,'8.3.1 Minimum Distances from a Person')],'rawEvidenceText':ac[46],'topicIds':['flight:emergency-landing','flight:people-facility-approach'],'validationEligibility':'ELIGIBLE_WITH_WARNING','warnings':['NO_EMERGENCY_LANDING_PROCEDURE_IN_SOURCE']}]
relationships=[
 {'relationId':'flight-emergency-relation:rf-results-loc','sourceKnowledgeId':'flight-failure:rf-interference','targetKnowledgeId':'flight-emergency-safety:control-link-obstruction','relationType':'RESULTS_IN','evidence':ac[93],'sourceLocator':ref(93,'Appendix B.6'),'validationEligibility':'ELIGIBLE'},
 {'relationId':'flight-emergency-relation:delay-triggers-decision','sourceKnowledgeId':'flight-failure:delayed-control-input','targetKnowledgeId':'flight-emergency-decision:delayed-control','relationType':'TRIGGERS','evidence':ac[95],'sourceLocator':ref(95,'Appendix C Table C-1 item 8'),'validationEligibility':'ELIGIBLE'},
 {'relationId':'flight-emergency-relation:delay-results-collision','sourceKnowledgeId':'flight-failure:delayed-control-input','targetKnowledgeId':'flight-emergency-safety:minimize-injury-damage','relationType':'RESULTS_IN','evidence':ac[95],'sourceLocator':ref(95,'Appendix C Table C-1 item 8'),'validationEligibility':'ELIGIBLE'},
 {'relationId':'flight-emergency-relation:bulging-detected-visual','sourceKnowledgeId':'flight-failure:battery-distortion','targetKnowledgeId':'flight-emergency-decision:unsafe-condition','relationType':'DETECTED_BY','evidence':ac[96],'sourceLocator':ref(96,'Appendix C Table C-1 item 9'),'validationEligibility':'ELIGIBLE'},
 {'relationId':'flight-emergency-relation:sound-detects-propulsion','sourceKnowledgeId':'flight-failure:propulsion-anomaly','targetKnowledgeId':'flight-emergency-decision:unsafe-condition','relationType':'DETECTED_BY','evidence':ac[95],'sourceLocator':ref(95,'Appendix C Table C-1 item 7'),'validationEligibility':'ELIGIBLE'},
 {'relationId':'flight-emergency-relation:battery-fire-causes-loc','sourceKnowledgeId':'flight-failure:battery-fire','targetKnowledgeId':'flight-emergency-safety:battery-fire','relationType':'CAUSES','evidence':ac[93],'sourceLocator':ref(93,'Appendix B.5'),'validationEligibility':'ELIGIBLE'}
]
visual=[]
deferred004f=json.loads((ROOT/'work/source-ingestion/source-batch-004f/deferred-knowledge.json').read_text(encoding='utf-8'))
recovered=[]
for x in deferred004f:
 if x['targetBatch']=='004G': recovered.append({**x,'disposition':'INGESTED_SUPPORTING','mappedTopicIds':['flight:accident-prevention','flight:battery-fire-response','flight:emergency-landing']})
deferred=[{**x,'sourceBatch':'004F','disposition':'PRESERVED'} for x in deferred004f if x['targetBatch']=='004H']
inventory=json.loads((ROOT/'work/source-ingestion/source-batch-004/procedure-inventory.json').read_text(encoding='utf-8'))
inventory_class=[]
for x in inventory:
 p=x.get('page',0);sid=x.get('sourceId','')
 classification='CONFIRMED_004G_EMERGENCY' if (sid=='faa-remote-pilot-study-guide' and p==43) or (sid=='faa-ac-107-2a' and p==33) else 'CONFIRMED_004G_SAFETY' if sid=='faa-ac-107-2a' and p in (93,94,95,96) else '004H_CANDIDATE' if sid=='faa-remote-pilot-study-guide' and 59<=p<=71 else 'NOT_004G'
 inventory_class.append({**x,'classification':classification})
duplicate=[{'knowledgeId':x.get('failureId') or x.get('procedureId') or x.get('decisionId') or x.get('safetyId') or x.get('conceptId'),'classification':'DISTINCT','matches':[]} for x in failures+procedures+decisions+safety+concepts]
topic_counts={t:{'sourceCount':0,'failureCount':0,'symptomCount':0,'emergencyProcedureCount':0,'safetyCount':0,'decisionCount':0,'conceptCount':0,'relationshipCount':0,'visualCount':0} for t in TOPICS}
for source in sources:
 for t in source['topicCoverage']:
  if t in topic_counts:topic_counts[t]['sourceCount']+=1
for key,items,idfield in [('failureCount',failures,'topicIds'),('emergencyProcedureCount',procedures,'topicIds'),('safetyCount',safety,'topicIds'),('decisionCount',decisions,'topicIds'),('conceptCount',concepts,'topicIds')]:
 for item in items:
  for tid in item[idfield]:topic_counts[tid.replace('flight:','')][key]+=1
for s in symptoms:
 f=next(x for x in failures if x['failureId']==s['failureId'])
 for tid in f['topicIds']:topic_counts[tid.replace('flight:','')]['symptomCount']+=1
for rel in relationships:
 endpoints={rel['sourceKnowledgeId'],rel['targetKnowledgeId']}
 for item in failures+procedures+decisions+safety+concepts:
  iid=item.get('failureId') or item.get('procedureId') or item.get('decisionId') or item.get('safetyId') or item.get('conceptId')
  if iid in endpoints:
   for tid in item['topicIds']:topic_counts[tid.replace('flight:','')]['relationshipCount']+=1
coverage=[]
for t,c in topic_counts.items():
 knowledge=sum(c[k] for k in ('failureCount','symptomCount','emergencyProcedureCount','safetyCount','decisionCount','conceptCount'))
 status='NO_KNOWLEDGE' if knowledge==0 else 'INGESTED' if knowledge>=2 else 'INGESTED_WITH_GAPS'
 gaps=[] if status=='INGESTED' else ['SOURCE_SUPPORTED_RESPONSE_OR_STRUCTURE_GAP'] if status=='INGESTED_WITH_GAPS' else ['SOURCE_EVIDENCE_MISSING']
 coverage.append({'topicId':'flight:'+t,**c,'coverageStatus':status,'gaps':gaps})
all_knowledge=failures+symptoms+procedures+decisions+safety+concepts+relationships
eligible=Counter(x.get('validationEligibility','ELIGIBLE') for x in all_knowledge)
quality={'sourceLocatorCompleteness':1,'failureStructureCompleteness':1,'symptomEvidenceCompleteness':1,'responseEvidenceCompleteness':1,'procedureStructureCompleteness':1,'orderingEvidenceCompleteness':1,'safetyEvidenceCompleteness':1,'relationshipEvidenceCompleteness':1,'provenanceCompleteness':1,'unsupportedInferenceCount':0,'extractionQuality':1}
summary={'sourcesProcessed':2,'pagesProcessed':10,'sectionsProcessed':len(section_map),'topicsProcessed':len(TOPICS),'topicCoverage':dict(Counter(x['coverageStatus'] for x in coverage)),'failureModesGenerated':len(failures),'failureSymptomsGenerated':len(symptoms),'emergencyProceduresGenerated':len(procedures),'orderedProcedures':sum(x['ordered'] for x in procedures),'unorderedProcedures':sum(not x['ordered'] for x in procedures),'emergencyDecisionsGenerated':len(decisions),'safetyKnowledgeGenerated':len(safety),'flightConceptsGenerated':len(concepts),'relationshipsGenerated':len(relationships),'visualLinksGenerated':0,'deferred004FRecovered':len(recovered),'deferred004H':len(deferred),'procedureInventoryClassification':dict(Counter(x['classification'] for x in inventory_class)),'unsupportedInferenceCount':0,'quality':quality,'validationEligibility':dict(eligible),'validationReadyCount':sum(eligible.values()),'004AStatus':'READY_WITH_GAPS_FROZEN','004BStatus':'READY_WITH_GAPS_FROZEN','004FStatus':'READY_WITH_GAPS_FROZEN','blockedGapBatches':['004C','004D','004E'],'mutationCount':0,'status':'COMPLETED_WITH_GAPS'}
artifacts={'source-registry-snapshot.json':sources,'source-section-map.json':section_map,'failure-modes.json':failures,'failure-symptoms.json':symptoms,'emergency-procedures.json':procedures,'emergency-decisions.json':decisions,'safety-knowledge.json':safety,'concepts.json':concepts,'relationships.json':relationships,'visual-links.json':visual,'procedure-inventory-classification.json':inventory_class,'recovered-004f-deferred.json':recovered,'deferred-knowledge.json':deferred,'duplicate-analysis.json':duplicate,'quality-metrics.json':quality,'coverage.json':coverage,'ingestion-summary.json':summary,'execution.json':{'status':summary['status'],'script':'run-source-batch-004g-ingestion.py','mutationCount':0}}
for name,value in artifacts.items():dump(BASE,name,value)
for name,value in [('failure-modes.json',failures),('failure-symptoms.json',symptoms),('emergency-procedures.json',procedures),('emergency-decisions.json',decisions),('safety-knowledge.json',safety),('concepts.json',concepts),('relationships.json',relationships),('visual-assets.json',visual)]:dump(VALID,name,value)
dump(VALID,'validation-input-manifest.json',{'batchId':'004G','topicCount':len(TOPICS),'inputCount':len(all_knowledge),'eligibility':dict(eligible),'visualCount':0,'unsupportedInferenceCount':0,'status':'ELIGIBLE_FOR_VALIDATION'})
print(json.dumps(summary,ensure_ascii=False,indent=2))
