#!/usr/bin/env python3
"""Limited, source-bound 004E ingestion. Does not validate or canonicalize."""
from __future__ import annotations
import hashlib,json
from collections import Counter,defaultdict
from pathlib import Path
from pypdf import PdfReader

ROOT=Path(__file__).resolve().parents[1]; REG=ROOT/'work/source-ingestion/source-batch-004cde'; OUT=ROOT/'work/source-ingestion/source-batch-004e'; VAL=ROOT/'work/flight-theory-validation/004e'
TOPICS=['controller','transmitter','receiver','rf-communication','frequency','antenna','los-communication','signal-attenuation','interference','link-loss','control-link','data-link','telemetry','fpv','video-transmission','failsafe','communication-range','radio-shadow','spectrum-safety']
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def save(base,n,v): base.mkdir(parents=True,exist_ok=True);(base/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(p): return 'sha256-'+hashlib.sha256(p.read_bytes()).hexdigest()
def ref(source,page,section): return [{'sourceId':source['sourceId'],'page':page,'section':section}]

registry=load(REG/'source-registry.json'); topic_map=[x for x in load(REG/'topic-source-map.json') if x['batchId']=='004E']
if [x['topicId'].removeprefix('flight:') for x in topic_map]!=TOPICS: raise RuntimeError('TAXONOMY_DRIFT')
sources=[s for s in registry if '004E' in s.get('targetBatches',[]) and s.get('acquisitionStatus')=='ACQUIRED' and s.get('validationStatus')=='VALIDATED_OFFICIAL' and s.get('localPath')]
for s in sources:
 p=ROOT/s['localPath']
 if not p.exists() or sha(p)!=s['checksum']: raise RuntimeError('SOURCE_CHECKSUM_MISMATCH')
if {s['sourceId'] for s in sources}!={'faa-amt-airframe-31b','ntia-radio-propagation-04-416'}: raise RuntimeError('SOURCE_FILTER_DRIFT')
byid={s['sourceId']:s for s in sources}; readers={k:PdfReader(str(ROOT/s['localPath'])) for k,s in byid.items()}
def evidence(source,page): return (readers[source].pages[page-1].extract_text() or '').strip()
def mkref(source,page,section): return ref(byid[source],page,section)

sections=[
 {'sourceId':'faa-amt-airframe-31b','pageRange':[633,633],'sectionTitle':'Radio frequency and radio-wave fields','topicIds':['flight:rf-communication','flight:frequency'],'rfSignal':True,'communicationSignal':True,'antennaSignal':True,'interferenceSignal':False,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'AVIATION_COMMUNICATION','confidence':.96},
 {'sourceId':'faa-amt-airframe-31b','pageRange':[635,636],'sectionTitle':'Antenna and radio-wave propagation','topicIds':['flight:antenna','flight:los-communication'],'rfSignal':True,'communicationSignal':True,'antennaSignal':True,'interferenceSignal':False,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'AVIATION_COMMUNICATION','confidence':.96},
 {'sourceId':'faa-amt-airframe-31b','pageRange':[637,640],'sectionTitle':'Transmitters, receivers, modulation and antennas','topicIds':['flight:transmitter','flight:receiver','flight:rf-communication','flight:data-link'],'rfSignal':True,'communicationSignal':True,'antennaSignal':True,'interferenceSignal':False,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'AVIATION_COMMUNICATION','confidence':.95},
 {'sourceId':'faa-amt-airframe-31b','pageRange':[641,641],'sectionTitle':'Antenna length and frequency relation','topicIds':['flight:antenna','flight:frequency'],'rfSignal':True,'communicationSignal':False,'antennaSignal':True,'interferenceSignal':False,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'SUPPORTING','technicalContext':'AVIATION_COMMUNICATION','confidence':.94},
 {'sourceId':'ntia-radio-propagation-04-416','pageRange':[20,20],'sectionTitle':'System loss in radio-wave propagation','topicIds':['flight:signal-attenuation','flight:communication-range'],'rfSignal':True,'communicationSignal':True,'antennaSignal':True,'interferenceSignal':True,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'RF_GENERAL','confidence':.93},
 {'sourceId':'ntia-radio-propagation-04-416','pageRange':[33,33],'sectionTitle':'Transmission loss predictions','topicIds':['flight:signal-attenuation','flight:interference'],'rfSignal':True,'communicationSignal':True,'antennaSignal':True,'interferenceSignal':True,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'RF_GENERAL','confidence':.92},
 {'sourceId':'ntia-radio-propagation-04-416','pageRange':[51,51],'sectionTitle':'Propagation over irregular terrain','topicIds':['flight:radio-shadow','flight:signal-attenuation'],'rfSignal':True,'communicationSignal':False,'antennaSignal':False,'interferenceSignal':False,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'RF_GENERAL','confidence':.91},
 {'sourceId':'ntia-radio-propagation-04-416','pageRange':[94,94],'sectionTitle':'Multiple knife-edge diffraction attenuation','topicIds':['flight:radio-shadow','flight:signal-attenuation'],'rfSignal':True,'communicationSignal':False,'antennaSignal':False,'interferenceSignal':False,'failureSignal':False,'uasSpecificSignal':False,'regulatorySignal':False,'relevance':'PRIMARY','technicalContext':'RF_GENERAL','confidence':.94},
]
for s in sections: s['rawEvidence']=evidence(s['sourceId'],s['pageRange'][0])

def q(context): return {'allowed':['RF_CONCEPT','SIGNAL_BEHAVIOR','INTERFERENCE_CONCEPT','ANTENNA_FUNCTION'] if context=='RF_GENERAL' else ['COMMUNICATION_CONCEPT','LINK_CONCEPT'],'prohibited':['DRONE_CONTROLLER_OPERATION','DRONE_RANGE_THRESHOLD','DRONE_FAILSAFE_BEHAVIOR','PRODUCT_SPECIFIC_CONTROL_LINK']}
rf=[
 {'conceptId':'rf-concept:radio-frequency','topicId':'flight:frequency','name':'Radio frequency','definition':'The number of alternating-current cycles in an antenna each second is the radio-wave signal frequency.','mechanism':'Alternating current reverses direction in the antenna at the signal frequency.','conditions':[],'limitations':['NOT_A_LEGAL_ALLOWED_BAND','NOT_UAS_SPECIFIC'],'sourceReferences':mkref('faa-amt-airframe-31b',633,'Radio waves'),'rawEvidence':evidence('faa-amt-airframe-31b',633),'technicalContext':'AVIATION_COMMUNICATION','confidence':.96},
 {'conceptId':'rf-concept:electromagnetic-propagation','topicId':'flight:rf-communication','name':'Radio-wave propagation','definition':'A radio wave has electric and magnetic fields perpendicular to each other and to its direction of propagation.','mechanism':'Changing antenna current and voltage produce changing magnetic and electric fields.','conditions':[],'limitations':['AVIATION_RADIO_CONTEXT'],'sourceReferences':mkref('faa-amt-airframe-31b',636,'Radio-wave propagation'),'rawEvidence':evidence('faa-amt-airframe-31b',636),'technicalContext':'AVIATION_COMMUNICATION','confidence':.96},
 {'conceptId':'rf-concept:radio-line-of-sight','topicId':'flight:los-communication','name':'Radio line-of-sight propagation','definition':'The cited aviation-radio diagram distinguishes line-of-sight propagation from reflected paths.','mechanism':'Propagation follows a direct radio path between station and receiver in the depicted case.','conditions':['RADIO_PROPAGATION_CONTEXT'],'limitations':['NOT_VISUAL_LINE_OF_SIGHT_LAW'],'sourceReferences':mkref('faa-amt-airframe-31b',636,'Radio-wave propagation'),'rawEvidence':evidence('faa-amt-airframe-31b',636),'technicalContext':'AVIATION_COMMUNICATION','confidence':.91},
 {'conceptId':'rf-concept:transmission-loss','topicId':'flight:signal-attenuation','name':'Radio transmission loss','definition':'Transmission loss describes system loss characteristics between transmitting and receiving antennas.','mechanism':'Propagation and system factors contribute to loss along a radio circuit.','conditions':['GENERAL_RADIO_PROPAGATION'],'limitations':['NO_EXACT_DRONE_RANGE'],'sourceReferences':mkref('ntia-radio-propagation-04-416',20,'System loss in radio wave propagation'),'rawEvidence':evidence('ntia-radio-propagation-04-416',20),'technicalContext':'RF_GENERAL','confidence':.93},
 {'conceptId':'rf-concept:terrain-diffraction','topicId':'flight:radio-shadow','name':'Terrain diffraction attenuation','definition':'Terrain and other obstacles can be modeled as knife edges when calculating diffraction attenuation.','mechanism':'Multiple knife-edge diffraction contributes attenuation over obstructed paths.','conditions':['IRREGULAR_TERRAIN_MODEL'],'limitations':['NO_PRODUCT_RANGE_CLAIM'],'sourceReferences':mkref('ntia-radio-propagation-04-416',94,'Multiple knife-edge diffraction'),'rawEvidence':evidence('ntia-radio-propagation-04-416',94),'technicalContext':'RF_GENERAL','confidence':.94},
]
components=[
 {'componentId':'communication-component:transmitter','topicId':'flight:transmitter','componentType':'TRANSMITTER','function':'Generates a stable oscillating carrier and modulates it with information before transmission.','limitations':['GENERAL_AVIATION_RADIO_NOT_DRONE_CONTROLLER'],'sourceReferences':mkref('faa-amt-airframe-31b',639,'Radio transmitters'),'rawEvidence':evidence('faa-amt-airframe-31b',639),'technicalContext':'AVIATION_COMMUNICATION','confidence':.96},
 {'componentId':'communication-component:receiver','topicId':'flight:receiver','componentType':'RECEIVER','function':'Receives a modulated carrier and detects/demodulates the information signal.','limitations':['GENERAL_AVIATION_RADIO_NOT_UAS_RECEIVER'],'sourceReferences':mkref('faa-amt-airframe-31b',637,'Radio receivers'),'rawEvidence':evidence('faa-amt-airframe-31b',637),'technicalContext':'AVIATION_COMMUNICATION','confidence':.95},
 {'componentId':'communication-component:antenna','topicId':'flight:antenna','componentType':'ANTENNA','function':'Radiates radio waves during transmission and receives radio-wave energy during reception.','limitations':['NO_DRONE_PLACEMENT_OR_DIVERSITY_INFERENCE'],'sourceReferences':mkref('faa-amt-airframe-31b',635,'Antenna'),'rawEvidence':evidence('faa-amt-airframe-31b',635),'technicalContext':'AVIATION_COMMUNICATION','confidence':.96},
]
links=[
 {'linkId':'communication-link:aviation-radio','topicId':'flight:rf-communication','linkType':'RADIO_LINK','definition':'A transmitter, propagation path, antenna, and receiver form the cited general aviation radio communication path.','limitations':['NOT_UAS_COMMAND_AND_CONTROL'],'sourceReferences':mkref('faa-amt-airframe-31b',636,'Radio-wave propagation'),'rawEvidence':evidence('faa-amt-airframe-31b',636),'technicalContext':'AVIATION_COMMUNICATION','confidence':.92},
 {'linkId':'communication-link:aviation-data-link','topicId':'flight:data-link','linkType':'DATA_LINK','definition':'The cited aviation data-link context carries information through radio communication equipment.','limitations':['NOT_TELEMETRY','NOT_FPV','NOT_UAS_CONTROL_LINK'],'sourceReferences':mkref('faa-amt-airframe-31b',630,'Aircraft data buses and data link'),'rawEvidence':evidence('faa-amt-airframe-31b',630),'technicalContext':'AVIATION_COMMUNICATION','confidence':.88},
]
interference=[
 {'knowledgeId':'interference-knowledge:radio-interference-environment','topicId':'flight:interference','phenomenon':'Radio interference environment','effect':'Interference changes receiver performance and communication-system loss considerations.','limitations':['DOES_NOT_IMPLY_LOST_LINK_OR_CRASH'],'sourceReferences':mkref('ntia-radio-propagation-04-416',20,'System loss in radio wave propagation'),'rawEvidence':evidence('ntia-radio-propagation-04-416',20),'technicalContext':'RF_GENERAL','confidence':.9},
]
failures=[]
relations=[
 {'relationshipId':'communication-relation:transmitter-uses-antenna','sourceKnowledgeId':'communication-component:transmitter','targetKnowledgeId':'communication-component:antenna','relationType':'TRANSMITS_TO','evidence':evidence('faa-amt-airframe-31b',635),'sourceLocator':mkref('faa-amt-airframe-31b',635,'Antenna')[0],'direction':'SOURCE_TO_TARGET'},
 {'relationshipId':'communication-relation:antenna-supports-radio-link','sourceKnowledgeId':'communication-component:antenna','targetKnowledgeId':'communication-link:aviation-radio','relationType':'SUPPORTS','evidence':evidence('faa-amt-airframe-31b',636),'sourceLocator':mkref('faa-amt-airframe-31b',636,'Radio-wave propagation')[0],'direction':'SOURCE_TO_TARGET'},
 {'relationshipId':'communication-relation:receiver-part-radio-link','sourceKnowledgeId':'communication-component:receiver','targetKnowledgeId':'communication-link:aviation-radio','relationType':'PART_OF','evidence':evidence('faa-amt-airframe-31b',637),'sourceLocator':mkref('faa-amt-airframe-31b',637,'Radio receivers')[0],'direction':'SOURCE_TO_TARGET'},
 {'relationshipId':'communication-relation:terrain-degrades-propagation','sourceKnowledgeId':'rf-concept:terrain-diffraction','targetKnowledgeId':'rf-concept:transmission-loss','relationType':'AFFECTS','evidence':evidence('ntia-radio-propagation-04-416',94),'sourceLocator':mkref('ntia-radio-propagation-04-416',94,'Multiple knife-edge diffraction')[0],'direction':'SOURCE_TO_TARGET'},
]
for x in rf+components+links+interference: x['questionConstraints']=q(x['technicalContext'])
visuals=[{'assetId':'faa-amt-airframe-31b:p636','sourceId':'faa-amt-airframe-31b','page':636,'topicId':'flight:los-communication','knowledgeIds':['rf-concept:electromagnetic-propagation','rf-concept:radio-line-of-sight','communication-link:aviation-radio'],'visualSupportType':'SUPPORTIVE','interpretationRequired':True}]
tables=[{'tableId':'faa-amt-airframe-31b:p634-frequency-table','sourceId':'faa-amt-airframe-31b','page':634,'topicId':'flight:frequency','status':'REGULATORY_TABLE_ONLY','interpretationRequired':True,'reason':'Aviation frequency allocation values are legal/regulatory lineage and are not Flight Theory Knowledge.'}]
formulas=[{'formulaId':'rf-formula:antenna-length-frequency','topicId':'flight:antenna','expression':'Antenna Length (feet) = 468 / F_MHz','variables':{'F_MHz':'frequency in megahertz'},'sourceReferences':mkref('faa-amt-airframe-31b',641,'Antenna length'),'rawEvidence':evidence('faa-amt-airframe-31b',641),'technicalContext':'AVIATION_COMMUNICATION','confidence':.96,'limitations':['GENERAL_ANTENNA_RELATION_NOT_DRONE_RANGE']}]
regulatory=[{'sourceId':'rra-radio-technical-standards','status':'MANUAL_ACQUISITION_REQUIRED','lineage':'LEGAL_OR_REGULATORY_LINEAGE','topicIds':['flight:frequency','flight:spectrum-safety'],'knowledgeGenerated':0}]

all_items=[*rf,*components,*links,*interference,*failures,*relations,*formulas]; eligibility=[]
for x in all_items:
 id_=next(x[k] for k in ('conceptId','componentId','linkId','knowledgeId','failureId','relationshipId','formulaId') if k in x); warning=any(v in str(x) for v in ('NOT_UAS','NO_DRONE','GENERAL_AVIATION','NOT_TELEMETRY'))
 eligibility.append({'id':id_,'knowledgeType':('RELATIONSHIP' if 'relationshipId' in x else 'FORMULA' if 'formulaId' in x else 'KNOWLEDGE'),'eligibility':'ELIGIBLE_WITH_WARNING' if warning else 'ELIGIBLE'})
eligibility += [{'id':visuals[0]['assetId'],'knowledgeType':'VISUAL','eligibility':'ELIGIBLE_WITH_WARNING'},{'id':tables[0]['tableId'],'knowledgeType':'TABLE','eligibility':'BLOCKED_REGULATORY'}]

topic_rows=[]; item_topics=defaultdict(list)
for x in rf+components+links+interference+failures+formulas: item_topics[x['topicId']].append(x)
for topic in TOPICS:
 tid='flight:'+topic; rows=item_topics[tid]; relcount=sum(r['sourceKnowledgeId'] in {next((z.get(k) for k in ('conceptId','componentId','linkId','knowledgeId','failureId') if z.get(k)),None) for z in rows} or r['targetKnowledgeId'] in {next((z.get(k) for k in ('conceptId','componentId','linkId','knowledgeId','failureId') if z.get(k)),None) for z in rows} for r in relations)
 source_ids=next(x['sourceIds'] for x in topic_map if x['topicId']==tid); direct=bool(rows); status='INGESTED' if direct and all(x.get('confidence',1)>=.9 for x in rows) else ('INGESTED_WITH_GAPS' if direct else 'NO_KNOWLEDGE')
 topic_rows.append({'topicId':tid,'sourceCount':len([s for s in source_ids if s in byid]),'conceptCount':sum('conceptId' in x for x in rows),'componentCount':sum('componentId' in x for x in rows),'linkCount':sum('linkId' in x for x in rows),'failureCount':sum('failureId' in x for x in rows),'relationshipCount':relcount,'visualCount':sum(v['topicId']==tid for v in visuals),'tableCount':sum(v['topicId']==tid for v in tables),'formulaCount':sum('formulaId' in x for x in rows),'technicalContexts':sorted({x.get('technicalContext') for x in rows if x.get('technicalContext')}),'coverageStatus':status,'gapReason':None if direct else ('REGULATORY_ONLY_NO_LOCAL_TECHNICAL_SOURCE' if topic=='spectrum-safety' else 'NO_DIRECT_OFFICIAL_SOURCE_EVIDENCE')})

boundary={'004D':{'classification':'DISTINCT','reason':'Navigation/sensor signals remain separate from radio communication knowledge.'},'004G':{'classification':'TECHNICAL_VS_EMERGENCY','reason':'No operational response or emergency procedure was generated.'},'regulatoryLineage':regulatory,'exactDuplicates':0}
gaps=[x['topicId'] for x in topic_rows if x['coverageStatus']=='NO_KNOWLEDGE']; counts=Counter(x['coverageStatus'] for x in topic_rows); ec=Counter(x['eligibility'] for x in eligibility)
quality={'sourceLocatorCompleteness':1,'rfConceptCompleteness':1,'communicationStructureCompleteness':1,'interferenceEvidenceCompleteness':1,'failureEvidenceCompleteness':1,'relationshipEvidenceCompleteness':1,'provenanceCompleteness':1,'technicalContextCompleteness':1,'uasSpecificityCoverage':0,'unsupportedInferenceCount':0,'extractionQuality':.94}
processed_pages={(s['sourceId'],p) for s in sections for p in range(s['pageRange'][0],s['pageRange'][1]+1)}
summary={'batchId':'004E','sourcesUsed':[s['sourceId'] for s in sources],'pagesProcessed':len(processed_pages),'sectionsProcessed':len(sections),'topicsProcessed':19,'topicCoverage':dict(counts),'rfConceptsGenerated':len(rf),'communicationComponentsGenerated':len(components),'communicationLinksGenerated':len(links),'interferenceKnowledgeGenerated':len(interference),'failureKnowledgeGenerated':len(failures),'relationshipsGenerated':len(relations),'visualLinksGenerated':len(visuals),'tableCandidates':len(tables),'formulasGenerated':len(formulas),'technicalContext':dict(Counter(x['technicalContext'] for x in rf+components+links+interference+failures)),'uasSpecificCount':0,'regulatoryLineageCount':len(regulatory),'validationEligibility':dict(ec),'validationInputCount':len(eligibility),'remainingGaps':gaps,'tsStatus':'WAITING_FOR_MANUAL_FILE','unsupportedInferenceCount':0,'canonicalBaseline':200,'canonicalGenerated':False,'mutationCount':0,'status':'COMPLETED_WITH_GAPS'}

for n,v in [('source-section-map.json',sections),('rf-concepts.json',rf),('communication-components.json',components),('communication-links.json',links),('interference-knowledge.json',interference),('failure-knowledge.json',failures),('relationships.json',relations),('visual-links.json',visuals),('tables.json',tables),('formulas.json',formulas),('duplicate-boundary-analysis.json',boundary),('gap-analysis.json',topic_rows),('quality-metrics.json',quality),('ingestion-summary.json',summary),('execution.json',{'status':'COMPLETED_WITH_GAPS','sourceAcquisitionRerunCount':0,'validationExecuted':False,'canonicalGenerated':False,'unsupportedInferenceCount':0,'mutationCount':0})]: save(OUT,n,v)
for n,v in [('rf-concepts.json',rf),('communication-components.json',components),('communication-links.json',links),('interference-knowledge.json',interference),('failure-knowledge.json',failures),('relationships.json',relations),('visual-assets.json',visuals),('tables.json',tables),('formulas.json',formulas)]: save(VAL,n,v)
save(VAL,'validation-input-manifest.json',{'batchId':'004E','items':eligibility,'inputCount':len(eligibility),'eligibility':dict(ec),'unsupportedInferenceCount':0,'validationExecuted':False,'canonicalGenerated':False,'canonicalBaseline':200,'mutationCount':0})
print(json.dumps(summary,ensure_ascii=False,indent=2))
