import {readFileSync} from "node:fs";import {join} from "node:path";import {describe,expect,it} from "vitest";
import {isUnsupportedRfGeneralization} from "./rf-concept-extractor";import {extractCommunicationLink} from "./communication-link-extractor";
type Summary={sourcesUsed:string[];topicsProcessed:number;topicCoverage:Record<string,number>;uasSpecificCount:number;unsupportedInferenceCount:number;canonicalBaseline:number;canonicalGenerated:boolean;mutationCount:number;remainingGaps:string[];validationInputCount:number};
type Execution={sourceAcquisitionRerunCount:number;validationExecuted:boolean;canonicalGenerated:boolean;mutationCount:number};type Boundary={"004D":{classification:string};"004G":{classification:string};regulatoryLineage:Array<{knowledgeGenerated:number}>};
const load=<T>(p:string)=>JSON.parse(readFileSync(join(process.cwd(),p),"utf8")) as T;
describe("SOURCE-BATCH-004E limited ingestion",()=>{
 const s=load<Summary>("work/source-ingestion/source-batch-004e/ingestion-summary.json");const e=load<Execution>("work/source-ingestion/source-batch-004e/execution.json");
 it("runs only 004E without acquisition, validation or Canonical generation",()=>{expect(s.topicsProcessed).toBe(19);expect(e.sourceAcquisitionRerunCount).toBe(0);expect(e.validationExecuted).toBe(false);expect(s.canonicalGenerated).toBe(false);});
 it.each(["transmitter becomes drone controller","RF link telemetry","data link FPV","interference lost-link","lost link failsafe","failsafe RTH","attenuation exact range"])("blocks unsupported inference: %s",text=>expect(isUnsupportedRfGeneralization(text)).toBe(true));
 it("does not promote a general radio link to telemetry",()=>{expect(()=>extractCommunicationLink({linkId:"x",linkType:"DATA_LINK",definition:"telemetry",sourceReferences:[{sourceId:"s",page:1,section:"x"}],rawEvidence:"x",technicalContext:"COMMUNICATION_GENERAL",confidence:1})).toThrow("UNSUPPORTED_UAS_LINK_GENERALIZATION");});
 it("keeps regulatory frequency lineage outside technical Knowledge",()=>{const b=load<Boundary>("work/source-ingestion/source-batch-004e/duplicate-boundary-analysis.json");expect(b.regulatoryLineage[0].knowledgeGenerated).toBe(0);const tables=load<Array<{status:string}>>("work/source-ingestion/source-batch-004e/tables.json");expect(tables[0].status).toBe("REGULATORY_TABLE_ONLY");});
 it("preserves 004D/004G boundaries and UAS gaps",()=>{const b=load<Boundary>("work/source-ingestion/source-batch-004e/duplicate-boundary-analysis.json");expect(b["004D"].classification).toBe("DISTINCT");expect(b["004G"].classification).toBe("TECHNICAL_VS_EMERGENCY");expect(s.uasSpecificCount).toBe(0);for(const id of ["flight:controller","flight:telemetry","flight:fpv","flight:link-loss","flight:failsafe"])expect(s.remainingGaps).toContain(id);});
 it("creates detached validation inputs without mutation",()=>{const m=load<{inputCount:number;validationExecuted:boolean;canonicalGenerated:boolean}>("work/flight-theory-validation/004e/validation-input-manifest.json");expect(m.inputCount).toBe(s.validationInputCount);expect(m.validationExecuted).toBe(false);expect(m.canonicalGenerated).toBe(false);expect(s.canonicalBaseline).toBe(200);expect(s.unsupportedInferenceCount).toBe(0);expect(e.mutationCount+s.mutationCount).toBe(0);});
});
